// =============================================================================
// GAZILLIONAIRE: STER DER HANDEL - Game Data
// =============================================================================

const PLANETEN = [
    {
        id: 'nexoria',
        naam: 'Nexoria',
        beschrijving: 'De grootste handelshub van de sector. Ideale startplek voor handelaars, met de Galactische Bank en alle scheepstypes te koop.',
        kleur: '#4a9eff',
        x: 50, y: 50,
        specialiteit: [],
        vraag: [],
        heeftBank: true,
        heeftWerf: true,
    },
    {
        id: 'ferrum',
        naam: 'Ferrum',
        beschrijving: 'Een rotsachtige mijnbouwplaneet vol mineralen. De arbeiders leven hard en de vraag naar allerlei goederen fluctueert sterk.',
        kleur: '#c8753a',
        x: 18, y: 28,
        specialiteit: [],
        vraag: [],
        heeftBank: false,
        heeftWerf: false,
    },
    {
        id: 'agria',
        naam: 'Agria',
        beschrijving: 'Een weelderige landbouwplaneet met uitgestrekte velden. Prijzen fluctueren naar gelang de oogst en exportvraag.',
        kleur: '#39a85a',
        x: 80, y: 22,
        specialiteit: [],
        vraag: [],
        heeftBank: false,
        heeftWerf: false,
    },
    {
        id: 'techton',
        naam: 'Techton',
        beschrijving: 'Het technologiecentrum van de sector. Fabrieken en labs draaien dag en nacht, met constant wisselende vraag naar grondstoffen.',
        kleur: '#9b59ff',
        x: 82, y: 72,
        specialiteit: [],
        vraag: [],
        heeftBank: true,
        heeftWerf: true,
    },
    {
        id: 'aqueron',
        naam: 'Aqueron',
        beschrijving: 'Een oceaanplaneet met uitgebreide biotechnologie. De handelspost is druk bezocht en prijzen reageren sterk op aanbod.',
        kleur: '#00aadd',
        x: 25, y: 75,
        specialiteit: [],
        vraag: [],
        heeftBank: false,
        heeftWerf: false,
    },
    {
        id: 'pyroflux',
        naam: 'Pyroflux',
        beschrijving: 'Een vulkanische planeet met enorme energiereserves. Extreme omstandigheden zorgen voor onvoorspelbare markten.',
        kleur: '#e03a3a',
        x: 12, y: 60,
        specialiteit: [],
        vraag: [],
        heeftBank: false,
        heeftWerf: false,
    },
    {
        id: 'luxoria',
        naam: 'Luxoria',
        beschrijving: 'Het rijkste resortplaneet van de melkweg. Exclusieve clientèle zorgt voor hoge omzet en grillige prijsbewegingen.',
        kleur: '#d4ac0d',
        x: 65, y: 88,
        specialiteit: [],
        vraag: [],
        heeftBank: true,
        heeftWerf: false,
    },
    {
        id: 'mortex',
        naam: 'Mortex Station',
        beschrijving: 'Een vervallen ruimtestation op de rand van het systeem. Hier gelden andere regels — hoge risico\'s en hoge beloningen. De zwarte markt bloeit.',
        kleur: '#8b0000',
        x: 48, y: 12,
        specialiteit: [],
        vraag: [],
        heeftBank: false,
        heeftWerf: false,
        isGevaarlijk: true,
    },
];

const GOEDEREN = [
    { id: 'ferroiet',     naam: 'Ferroiet',     icoon: '🔩', basisPrijs: 50,  gewicht: 1, beschrijving: 'Basismetaal voor bouw en productie' },
    { id: 'kristalliet',  naam: 'Kristalliet',  icoon: '💠', basisPrijs: 115, gewicht: 1, beschrijving: 'Energiekristallen voor reactoren en shields' },
    { id: 'nebulakorrels',naam: 'Nebulakorrels',icoon: '🌾', basisPrijs: 32,  gewicht: 2, beschrijving: 'Voedzame graankorrels; basisvoedsel voor kolonies' },
    { id: 'bioplasma',    naam: 'Bioplasma',    icoon: '💉', basisPrijs: 175, gewicht: 1, beschrijving: 'Medische basistof voor behandelingen' },
    { id: 'technoware',   naam: 'Technoware',   icoon: '🔌', basisPrijs: 145, gewicht: 1, beschrijving: 'Elektronische componenten en modules' },
    { id: 'quantumchips', naam: 'Quantumchips', icoon: '💾', basisPrijs: 375, gewicht: 1, beschrijving: 'Geavanceerde kwantumprocessors' },
    { id: 'aquapure',     naam: 'Aquapure',     icoon: '💧', basisPrijs: 42,  gewicht: 3, beschrijving: 'Gezuiverd water voor menselijke kolonies' },
    { id: 'pyrogel',      naam: 'Pyrogel',      icoon: '⛽', basisPrijs: 82,  gewicht: 2, beschrijving: 'Hoogenergetische ruimtebrandstof' },
    { id: 'luxuriet',     naam: 'Luxuriet',     icoon: '👑', basisPrijs: 440, gewicht: 1, beschrijving: 'Allerhande luxe artikelen en statussymbolen' },
    { id: 'lunasteen',    naam: 'Lunasteen',    icoon: '💎', basisPrijs: 310, gewicht: 1, beschrijving: 'Zeldzame edelstenen van buitenste manen' },
];

const SCHEPEN = [
    {
        id: 'rondsloffer',
        naam: 'Rondsloffer',
        icoon: '🛸',
        beschrijving: 'Een oude, vertrouwde transportschuit. Langzaam en bouwvallig, maar betaalbaar voor beginnende handelaars.',
        prijs: 3000,
        snelheid: 1,
        laadruimte: 30,
        schild: 1,
        kleur: '#888',
        passagiersCapaciteit: 0,
        brandstofTank: 80,
    },
    {
        id: 'handelaar',
        naam: 'Vrije Handelaar',
        icoon: '🚀',
        beschrijving: 'Het klassieke handelsschip. Een goede balans tussen snelheid, laadruimte en prijs. De keuze van de doorgewinterde ruimtekoopman.',
        prijs: 6000,
        snelheid: 2,
        laadruimte: 50,
        schild: 2,
        kleur: '#4a9eff',
        passagiersCapaciteit: 2,
        brandstofTank: 110,
    },
    {
        id: 'vleugelschipper',
        naam: 'Vleugelschipper',
        icoon: '✈️',
        beschrijving: 'Snel en wendbaar, maar met een kleine laadruimte. Ideaal voor handelaars die snelheid boven volume verkiezen.',
        prijs: 9500,
        snelheid: 4,
        laadruimte: 35,
        schild: 1,
        kleur: '#ff6b35',
        passagiersCapaciteit: 4,
        brandstofTank: 70,
    },
];

const UPGRADES = [
    {
        id: 'schild_mk2',
        naam: 'Energieschild Mk.II',
        categorie: 'schild',
        beschrijving: 'Betere bescherming bij gevaarlijke events. +1 schildwaarde.',
        icoon: '🛡️',
        prijs: 2200,
        vereist: null,
        effect: { schild: 1 },
        niveau: 1,
    },
    {
        id: 'schild_mk3',
        naam: 'Militair Schild',
        categorie: 'schild',
        beschrijving: 'Soldatenkwaliteit defensie. +2 schildwaarde extra.',
        icoon: '🔰',
        prijs: 6500,
        vereist: 'schild_mk2',
        effect: { schild: 2 },
        niveau: 2,
    },
    {
        id: 'radar',
        naam: 'Handelsradar',
        categorie: 'extra',
        beschrijving: 'Toont prijstrends (↑↓) op de markt. Onmisbaar voor slimme handelaars.',
        icoon: '📡',
        prijs: 3500,
        vereist: null,
        effect: { radar: true },
        niveau: 1,
    },
];

// Kansen optellen naar 1.0
const EVENTS = [
    {
        id: 'piraten',
        naam: 'Ruimtepiraten!',
        icoon: '☠️',
        type: 'gevaar',
        kans: 0.10,
        beschrijving: 'Een piratengroep onderschept je schip en blokkeert je route. Ze eisen tol voor veilige doorgang.',
        heeftKeuze: true,
        keuzes: [
            { id: 'betaal', tekst: 'Betaal het losgeld', stijl: 'gevaar' },
            { id: 'vlucht', tekst: 'Probeer te ontsnappen', stijl: 'knop' },
        ],
    },
    {
        id: 'stralingstorm',
        naam: 'Stralingstorm',
        icoon: '⚡',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een zware stralingstorm treft je route. Je moet een grote omweg nemen — dat kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'ruimtewrak',
        naam: 'Ruimtewrak Gevonden',
        icoon: '🛸',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Je detecteert een verlaten handelsschip. Na onderzoek vind je nog bruikbare lading aan boord!',
        heeftKeuze: false,
    },
    {
        id: 'defect',
        naam: 'Mechanisch Defect',
        icoon: '🔧',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een cruciaal onderdeel geeft het op. Je moet halverwege stoppen voor noodreparaties.',
        heeftKeuze: true,
        keuzes: [
            { id: 'repareer', tekst: 'Repareer direct (400 cr)', stijl: 'gevaar' },
            { id: 'doorvaren', tekst: 'Doorvaren met beschadiging', stijl: 'knop' },
        ],
    },
    {
        id: 'smokkelbod',
        naam: 'Sluiksmokkelaar',
        icoon: '🤫',
        type: 'kans',
        kans: 0.07,
        beschrijving: 'Een mysterieuze smokkelaar biedt je goederen aan ver onder de marktprijs. Riskant, maar potentieel winstgevend.',
        heeftKeuze: true,
        keuzes: [
            { id: 'koop', tekst: 'Koop de goederen', stijl: 'succes' },
            { id: 'weiger', tekst: 'Weiger het aanbod', stijl: 'knop' },
        ],
    },
    {
        id: 'nevel',
        naam: 'Ionennevel',
        icoon: '🌫️',
        type: 'neutraal',
        kans: 0.08,
        beschrijving: 'Je vliegt door een dichte ionennevel. Navigatiesystemen raken verstoord — de omweg kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'tip',
        naam: 'Handelstip',
        icoon: '💡',
        type: 'kans',
        kans: 0.09,
        beschrijving: 'Je ontmoet een vriendelijke ruimtekapitein die je een waardevolle tip geeft over de marktprijzen!',
        heeftKeuze: false,
    },
    {
        id: 'asteroiden',
        naam: 'Asteroïdenveld',
        icoon: '🪨',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Je vliegt onverwacht een dicht asteroïdenveld in. Je schip loopt averij op!',
        heeftKeuze: false,
    },
    {
        id: 'douane',
        naam: 'Douanecontrole',
        icoon: '🔍',
        type: 'neutraal',
        kans: 0.07,
        beschrijving: 'Galactische douaniers stoppen je voor een grondige controle. Ze kijken of alles in orde is.',
        heeftKeuze: false,
    },
    {
        id: 'bonus',
        naam: 'Galactische Subsidie',
        icoon: '🎁',
        type: 'kans',
        kans: 0.06,
        beschrijving: 'Gefeliciteerd! Je ontvangt een onverwachte handelssubsidie van de Galactische Handelsgilde!',
        heeftKeuze: false,
    },
    {
        id: 'brandstof_vraag',
        naam: 'Noodoproep: Brandstof',
        icoon: '🆘',
        type: 'neutraal',
        kans: 0.05,
        beschrijving: 'Een gestrande ruimtepiloot roept je via de noodfrequentie op. Ze zit zonder brandstof en vraagt om hulp.',
        heeftKeuze: true,
        keuzes: [
            { id: 'geef', tekst: 'Geef 20 liter brandstof', stijl: 'succes' },
            { id: 'weiger', tekst: 'Vlieg door', stijl: 'knop' },
        ],
    },
    {
        id: 'lifter',
        naam: 'Ruimtelift Gevraagd',
        icoon: '🧳',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Een reiziger wil meelliften naar je bestemming.', // dynamic in UI
        heeftKeuze: true,
        keuzes: [
            { id: 'meenemen', tekst: 'Neem de lifter mee', stijl: 'succes' },
            { id: 'weiger', tekst: 'Rijd door', stijl: 'knop' },
        ],
    },
    {
        id: 'bederf',
        naam: 'Goederen Bedorven!',
        icoon: '🤢',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Door een storing in je koelsysteem zijn een deel van je goederen bedorven. Je verliest de helft!',
        heeftKeuze: false,
    },
    {
        id: 'haven_gesloten',
        naam: 'Ruimtehaven Gesloten',
        icoon: '🚫',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'De ruimtehaven van je bestemming is plotseling gesloten vanwege een quarantaineprotocol. Je moet noodkoers zetten naar de dichtstbijzijnde alternatieve haven.',
        heeftKeuze: false,
    },
    {
        id: 'noodlanding',
        naam: 'Noodlanding',
        icoon: '🆘',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een kritische motorsysteem storing dwingt je tot een noodlanding op de dichtstbijzijnde planeet. Je geplande bestemming is niet meer haalbaar.',
        heeftKeuze: false,
    },
    {
        id: 'douaneboete',
        naam: 'Galactische Douaneboete',
        icoon: '🚨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Douaneinspecteurs leggen een fikse boete op wegens een papierwerk-overtreding. Je moet direct betalen.',
        heeftKeuze: false,
    },
    {
        id: 'cargo_lek',
        naam: 'Containerlek',
        icoon: '💨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Een container heeft een druklek. Kostbare lading is in de ruimte verdwenen voor je het door had.',
        heeftKeuze: false,
    },
    {
        id: 'motordiefstal',
        naam: 'Ruimtediefstal',
        icoon: '🦹',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'Een listige ruimtecrimineel heeft onopgemerkt je vrachtruim doorzocht en credits buitgemaakt.',
        heeftKeuze: false,
    },
    {
        id: 'niets',
        naam: 'Rustige reis',
        icoon: '🌟',
        type: 'neutraal',
        kans: 0.18,
        beschrijving: 'De reis verloopt vlekkeloos. Sterrenbeelden passeren, je koers is recht, en alles is in orde.',
        heeftKeuze: false,
    },
];

const AANDELEN = [
    { id: 'nexcorp',    naam: 'NexCorp Mining',    icoon: '⛏️', basisPrijs: 100, beschrijving: 'Mijnbouwconglomeraat actief op Ferrum' },
    { id: 'aquatech',   naam: 'AquaTech',           icoon: '💧', basisPrijs: 75,  beschrijving: 'Waterbehandeling en distributie' },
    { id: 'pyroenergie',naam: 'PyroEnergie NV',     icoon: '⚡', basisPrijs: 110, beschrijving: 'Brandstofproducent op Pyroflux' },
    { id: 'luxtrading', naam: 'LuxTrading Corp',    icoon: '💰', basisPrijs: 180, beschrijving: 'Premium luxehandel gericht op Luxoria' },
    { id: 'techstar',   naam: 'TechStar Industries',icoon: '🌟', basisPrijs: 140, beschrijving: 'Technologiepionier en innovator' },
    { id: 'biomed',     naam: 'BioMed Galax',       icoon: '💊', basisPrijs: 85,  beschrijving: 'Farmaceutisch concern met basis op Aqueron' },
];

const CONCURRENTEN = [
    {
        id: 'zax',
        naam: 'Handelaar Zax',
        icoon: '🦊',
        persoonlijkheid: 'Opportunist',
        beschrijving: 'Een nietsontziende opkoper die elke kans aangrijpt. Snel, gretig, en overal tegelijk aanwezig.',
        snelheid: 3,
        kleur: '#ff6b35',
        startKrediet: 4500,
        baseWinstPerBeurt: 900,
        volatiliteit: 0.13,
    },
    {
        id: 'mira',
        naam: 'Koopman Mira',
        icoon: '💼',
        persoonlijkheid: 'Strateeg',
        beschrijving: 'Berekend en gedisciplineerd. Mira plant elke zet en maakt zelden een fout — de gevaarlijkste concurrent.',
        snelheid: 2,
        kleur: '#00d4ff',
        startKrediet: 5500,
        baseWinstPerBeurt: 1100,
        volatiliteit: 0.05,
    },
    {
        id: 'rok',
        naam: 'Kapitein Rok',
        icoon: '⚡',
        persoonlijkheid: 'Avonturier',
        beschrijving: 'Onstuimig en razendsnel. Rok pikt de beste deals weg voor jij ze ziet, maar maakt ook spectaculaire missers.',
        snelheid: 4,
        kleur: '#ffd700',
        startKrediet: 3000,
        baseWinstPerBeurt: 850,
        volatiliteit: 0.10,
    },
    {
        id: 'voss',
        naam: 'Makelaar Voss',
        icoon: '🎩',
        persoonlijkheid: 'Veteraan',
        beschrijving: 'De oude reus van de handelswereld. Traag, maar zijn netwerk en ervaring leveren hem altijd een voordeel op.',
        snelheid: 1,
        kleur: '#9b59ff',
        startKrediet: 7000,
        baseWinstPerBeurt: 800,
        volatiliteit: 0.04,
    },
    {
        id: 'nyx',
        naam: 'Schaduw Nyx',
        icoon: '🕶️',
        persoonlijkheid: 'Mysterie',
        beschrijving: 'Niemand weet precies wat Nyx doet. Zijn vermogen fluctueert wild — soms verdwijnt het plots, soms verveelvoudigt het.',
        snelheid: 3,
        kleur: '#ff3855',
        startKrediet: 5000,
        baseWinstPerBeurt: 600,
        volatiliteit: 0.22,
    },
];

const ACHIEVEMENTS = [
    {
        id: 'eerste_deal',
        naam: 'Eerste Deal',
        icoon: '🤝',
        categorie: 'deals',
        beschrijving: 'Voltooi je eerste handelstransactie.',
        beloning: 250,
        check: s => s.statistieken.handelstransacties >= 1,
    },
    {
        id: 'tiental',
        naam: 'Actieve Handelaar',
        icoon: '📊',
        categorie: 'deals',
        beschrijving: 'Voltooi 10 handelstransacties.',
        beloning: 750,
        check: s => s.statistieken.handelstransacties >= 10,
    },
    {
        id: 'vijftig',
        naam: 'Handelsmagnaat',
        icoon: '🏪',
        categorie: 'deals',
        beschrijving: 'Voltooi 50 handelstransacties.',
        beloning: 3000,
        check: s => s.statistieken.handelstransacties >= 50,
    },
    {
        id: 'rijkaard',
        naam: 'Rijkaard',
        icoon: '💰',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 10.000 credits.',
        beloning: 1500,
        check: s => s.berekenNettowaarde() >= 10000,
    },
    {
        id: 'groot_handelaar',
        naam: 'Groot Handelaar',
        icoon: '🏛️',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 100.000 credits.',
        beloning: 7500,
        check: s => s.berekenNettowaarde() >= 100000,
    },
    {
        id: 'millionair',
        naam: 'Galactische Millionair',
        icoon: '🌟',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 1.000.000 credits.',
        beloning: 50000,
        check: s => s.berekenNettowaarde() >= 1000000,
    },
    {
        id: 'wereldreiziger',
        naam: 'Wereldreiziger',
        icoon: '🗺️',
        categorie: 'events',
        beschrijving: 'Bezoek alle 8 planeten.',
        beloning: 5000,
        check: s => s.bezochteplaneten && s.bezochteplaneten.size >= 8,
    },
    {
        id: 'motor_fanaat',
        naam: 'Motorfanaat',
        icoon: '🔥',
        categorie: 'schip',
        beschrijving: 'Installeer de Motor Mk.III.',
        beloning: 2000,
        check: s => (s.upgradeNiveaus?.motor ?? 0) >= 3,
    },
    {
        id: 'beurs_goeroe',
        naam: 'Beursgoeroe',
        icoon: '📈',
        categorie: 'beurs',
        beschrijving: 'Bezit 4 of meer verschillende aandelen tegelijk.',
        beloning: 2500,
        check: s => Object.values(s.aandelenPortefeuille).filter(v => v > 0).length >= 4,
    },
    {
        id: 'winstmaker',
        naam: 'Winstmaker',
        icoon: '💎',
        categorie: 'deals',
        beschrijving: 'Maak 1.000 credits winst op één deal.',
        beloning: 1500,
        check: s => s._laatsteWinst >= 1000,
    },
    {
        id: 'superdeal',
        naam: 'Superdeal',
        icoon: '🏆',
        categorie: 'deals',
        beschrijving: 'Maak 5.000 credits winst op één deal.',
        beloning: 5000,
        check: s => s._laatsteWinst >= 5000,
    },
    {
        id: 'reiziger',
        naam: 'Ruimtereiziger',
        icoon: '🚀',
        categorie: 'events',
        beschrijving: 'Maak 10 ruimtereizen.',
        beloning: 1500,
        check: s => s.statistieken.gereisd >= 10,
    },
    {
        id: 'schuldenvrij',
        naam: 'Schuldenvrij',
        icoon: '✅',
        categorie: 'nettowaarde',
        beschrijving: 'Betaal een lening volledig af.',
        beloning: 2000,
        check: s => s._oitLeningGehad && s.speler.schuld === 0,
    },
    {
        id: 'vol_ruim',
        naam: 'Tot de Nok Gevuld',
        icoon: '📦',
        categorie: 'deals',
        beschrijving: 'Vul je laadruimte volledig.',
        beloning: 500,
        check: s => s.schip && s.getLadingGewicht() >= s.schip.laadruimte,
    },
    {
        id: 'overlever',
        naam: 'Piratenontkomer',
        icoon: '⚡',
        categorie: 'events',
        beschrijving: 'Ontsnapt aan piraten.',
        beloning: 1000,
        check: s => s._piratenOntkomingen > 0,
    },
    {
        id: 'bijna_leeg',
        naam: 'Op de Rand',
        icoon: '⛽',
        categorie: 'events',
        beschrijving: 'Kom aan op een planeet met minder dan 10 liter brandstof.',
        beloning: 300,
        check: s => s._aangekomendMetLageBrandstof,
    },
    {
        id: 'eerste_passagier',
        naam: 'Taxiservice',
        icoon: '🧳',
        categorie: 'events',
        beschrijving: 'Lever je eerste passagier af op zijn bestemming.',
        beloning: 600,
        check: s => s.statistieken.passagiersAfgeleverd >= 1,
    },
];

// =============================================================================
// PLANEET AANKOMST EVENTS — spelen af bij landing op een planeet
// =============================================================================
const PLANEET_EVENTS = [
    {
        id: 'gewapend_conflict',
        naam: 'Gewapend Conflict',
        icoon: '⚔️',
        kans: 0.05,
        beschrijving: 'Een gewapend conflict heeft de aanvoerroutes verstoord. Technoware en Quantumchips zijn tijdelijk 80% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['technoware', 'quantumchips'], factor: 1.8 },
    },
    {
        id: 'handelsfestival',
        naam: 'Handelsfestival',
        icoon: '🎪',
        kans: 0.07,
        beschrijving: 'De jaarlijkse galactische handelsmarkt is in volle gang! Alle goederen zijn vandaag 15% goedkoper.',
        effect: { type: 'kortingAlles', factor: 0.85 },
    },
    {
        id: 'rijke_oogst',
        naam: 'Overrijke Oogst',
        icoon: '🌾',
        kans: 0.06,
        beschrijving: 'Een uitzonderlijk goede oogst heeft de voedselmarkt overspoeld. Nebulakorrels en Aquapure zijn spotgoedkoop.',
        effect: { type: 'prijsVerlaging', goederen: ['nebulakorrels', 'aquapure'], factor: 0.5 },
    },
    {
        id: 'energiecrisis',
        naam: 'Energiecrisis',
        icoon: '🔋',
        kans: 0.05,
        beschrijving: 'Een storing in de energiecentrale heeft de haven getroffen. Pyrogel en Kristalliet zijn vandaag extra duur.',
        effect: { type: 'prijsVerhoging', goederen: ['pyrogel', 'kristalliet'], factor: 2.0 },
    },
    {
        id: 'tech_doorbraak',
        naam: 'Technologische Doorbraak',
        icoon: '🔬',
        kans: 0.05,
        beschrijving: 'Lokale wetenschappers maakten een baanbrekende ontdekking. Technoware en Quantumchips zijn tijdelijk 35% goedkoper.',
        effect: { type: 'prijsVerlaging', goederen: ['technoware', 'quantumchips'], factor: 0.65 },
    },
    {
        id: 'piraten_aanval',
        naam: 'Pirateninval',
        icoon: '💀',
        kans: 0.04,
        beschrijving: 'Piraten hebben de haven aangevallen tijdens jouw landing. Een deel van je lading is gestolen!',
        effect: { type: 'ladingStelen', fractie: 0.1 },
    },
    {
        id: 'markt_crash',
        naam: 'Lokale Marktcrash',
        icoon: '📉',
        kans: 0.04,
        beschrijving: 'Speculanten hebben de lokale markt doen crashen. Alle goederen zijn vandaag 20% goedkoper — maar kopers zijn ook schaars.',
        effect: { type: 'kortingAlles', factor: 0.8 },
    },
    {
        id: 'zwarte_markt',
        naam: 'Zwarte Markt Actief',
        icoon: '🕵️',
        kans: 0.05,
        beschrijving: 'Een ondergrondse markt biedt Luxuriet en Lunasteen aan voor slechts de helft van de normale prijs. Grijp je kans!',
        effect: { type: 'prijsVerlaging', goederen: ['luxuriet', 'lunasteen'], factor: 0.5 },
    },
    {
        id: 'handelsblokkade',
        naam: 'Galactische Handelsblokkade',
        icoon: '🚫',
        kans: 0.03,
        beschrijving: 'Autoriteiten hebben een handelsblokkade uitgevaardigd. Luxe goederen en edelstenen zijn 60% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['luxuriet', 'lunasteen'], factor: 1.6 },
    },
    {
        id: 'voedselschaarste',
        naam: 'Voedselschaarste',
        icoon: '🆘',
        kans: 0.05,
        beschrijving: 'Een mislukte oogst heeft geleid tot ernstige voedseltekorten. Nebulakorrels en Aquapure zijn enorm in prijs gestegen!',
        effect: { type: 'prijsVerhoging', goederen: ['nebulakorrels', 'aquapure'], factor: 2.2 },
    },
    {
        id: 'mijnwerkerstaking',
        naam: 'Mijnwerkerstaking',
        icoon: '✊',
        kans: 0.05,
        beschrijving: 'Mijnwerkers staken voor betere arbeidsomstandigheden. Ferroiet en Kristalliet zijn tijdelijk niet te krijgen voor normale prijs.',
        effect: { type: 'prijsVerhoging', goederen: ['ferroiet', 'kristalliet'], factor: 1.9 },
    },
];
