// =============================================================================
// GAZILLIONAIRE: STER DER HANDEL - Game Data
// =============================================================================

const PLANETEN = [
    {
        id: 'nexoria',
        naam: 'Nexoria',
        beschrijving: 'De grootste handelshub van de sector. Ideale startplek voor handelaars, met de aandelenbeurs en een volledig uitgeruste bank.',
        kleur: '#4a9eff',
        x: 50, y: 50,
        specialiteit: [],
        vraag: [],
    },
    {
        id: 'ferrum',
        naam: 'Ferrum',
        beschrijving: 'Een rotsachtige mijnbouwplaneet vol mineralen. De arbeiders leven hard en de vraag naar allerlei goederen fluctueert sterk.',
        kleur: '#c8753a',
        x: 18, y: 28,
        specialiteit: ['ferroiet', 'lunasteen'],
        vraag: ['nebulakorrels', 'aquapure'],
    },
    {
        id: 'agria',
        naam: 'Agria',
        beschrijving: 'Een weelderige landbouwplaneet met uitgestrekte velden. Prijzen fluctueren naar gelang de oogst en exportvraag.',
        kleur: '#39a85a',
        x: 80, y: 22,
        specialiteit: ['nebulakorrels', 'aquapure'],
        vraag: ['technoware', 'quantumchips'],
    },
    {
        id: 'techton',
        naam: 'Techton',
        beschrijving: 'Het technologiecentrum van de sector. Fabrieken en labs draaien dag en nacht, met constant wisselende vraag naar grondstoffen.',
        kleur: '#9b59ff',
        x: 82, y: 72,
        specialiteit: ['technoware', 'quantumchips'],
        vraag: ['pyrogel', 'ferroiet'],
    },
    {
        id: 'aqueron',
        naam: 'Aqueron',
        beschrijving: 'Een oceaanplaneet met uitgebreide biotechnologie. De handelspost is druk bezocht en prijzen reageren sterk op aanbod.',
        kleur: '#00aadd',
        x: 25, y: 75,
        specialiteit: ['bioplasma', 'aquapure'],
        vraag: ['luxuriet', 'lunasteen'],
    },
    {
        id: 'pyroflux',
        naam: 'Pyroflux',
        beschrijving: 'Een vulkanische planeet met enorme energiereserves. Extreme omstandigheden zorgen voor onvoorspelbare markten.',
        kleur: '#e03a3a',
        x: 12, y: 60,
        specialiteit: ['pyrogel', 'kristalliet'],
        vraag: ['nebulakorrels', 'bioplasma'],
    },
    {
        id: 'luxoria',
        naam: 'Luxoria',
        beschrijving: 'Het rijkste resortplaneet van de melkweg. Exclusieve clientèle zorgt voor hoge omzet en grillige prijsbewegingen.',
        kleur: '#d4ac0d',
        x: 65, y: 88,
        specialiteit: ['luxuriet', 'lunasteen'],
        vraag: ['ferroiet', 'pyrogel'],
    },
    {
        id: 'mortex',
        naam: 'Mortex Station',
        beschrijving: 'Vervallen station aan de rand van het systeem. Andere regels, hoge risico\'s, hoge beloningen — de zwarte markt bloeit.',
        kleur: '#8b0000',
        x: 48, y: 12,
        specialiteit: [],
        vraag: [],
        isGevaarlijk: true,
    },
];

const GOEDEREN = [
    { id: 'ferroiet',     naam: 'Ferroiet',     icoon: 'assets/ferroiet.png',     basisPrijs: 50,  beschrijving: 'Basismetaal voor bouw en productie' },
    { id: 'kristalliet',  naam: 'Kristalliet',  icoon: 'assets/kristalliet.png',  basisPrijs: 115, beschrijving: 'Energiekristallen voor reactoren en shields' },
    { id: 'nebulakorrels',naam: 'Nebulakorrels',icoon: 'assets/nebulakorrels.png',basisPrijs: 32,  beschrijving: 'Voedzame graankorrels; basisvoedsel voor kolonies' },
    { id: 'bioplasma',    naam: 'Bioplasma',    icoon: 'assets/bioplasma.png',    basisPrijs: 175, beschrijving: 'Medische basistof voor behandelingen' },
    { id: 'technoware',   naam: 'Technoware',   icoon: 'assets/technoware.png',   basisPrijs: 145, beschrijving: 'Elektronische componenten en modules' },
    { id: 'quantumchips', naam: 'Quantumchips', icoon: 'assets/quantumchips.png', basisPrijs: 375, beschrijving: 'Geavanceerde kwantumprocessors' },
    { id: 'aquapure',     naam: 'Aquapure',     icoon: 'assets/aquapure.png',     basisPrijs: 42,  beschrijving: 'Gezuiverd water voor menselijke kolonies' },
    { id: 'pyrogel',      naam: 'Pyrogel',      icoon: 'assets/pyrogel.png',      basisPrijs: 82,  beschrijving: 'Hoogenergetische ruimtebrandstof' },
    { id: 'luxuriet',     naam: 'Luxuriet',     icoon: 'assets/luxuriet.png',     basisPrijs: 440, beschrijving: 'Allerhande luxe artikelen en statussymbolen' },
    { id: 'lunasteen',    naam: 'Lunasteen',    icoon: 'assets/lunasteen.png',    basisPrijs: 310, beschrijving: 'Zeldzame edelstenen van buitenste manen' },
];

/**
 * Renders a resource icon as an <img> for PNG assets, or a <span> for emoji fallbacks.
 * @param {string} icoon - asset path (e.g. 'assets/ferroiet.png') or emoji
 * @param {string} [alt] - alt text for the img
 * @returns {string} HTML string
 */
function goedIcoonHtml(icoon, alt = '') {
    if (typeof icoon === 'string' && icoon.startsWith('assets/')) {
        return `<img src="${icoon}" class="res-icoon" alt="${alt}">`;
    }
    return `<span class="res-emoji">${icoon}</span>`;
}

const SCHEPEN = [
    // === VRACHTSCHIP ===
    {
        id: 'vracht_1',
        type: 'vracht',
        mark: 1,
        specialisatie: null,
        naam: 'Vrachtschip Mark I',
        icoon: '🚛',
        beschrijving: 'Robuust vrachtschip. Langzaam maar met ruim laadvermogen. De ruggengraat van de interplanetaire handel.',
        prijs: 16000,
        snelheid: 1,
        laadruimte: 60,
        schild: 2,
        kleur: '#8B6914',
        passagiersCapaciteit: 2,
        brandstofTank: 100,
        maxHP: 50,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_2',
        type: 'vracht',
        mark: 2,
        specialisatie: null,
        naam: 'Vrachtschip Mark II',
        icoon: '🚛',
        beschrijving: 'Verbeterd vrachtschip met grotere laadruimte en verstevigde romp. Bewezen workhorse.',
        prijs: 65000,
        snelheid: 1,
        laadruimte: 100,
        schild: 3,
        kleur: '#A07820',
        passagiersCapaciteit: 3,
        brandstofTank: 120,
        maxHP: 70,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_3a',
        type: 'vracht',
        mark: 3,
        specialisatie: 'a',
        naam: 'Tanker Mark III',
        icoon: '🛢️',
        beschrijving: 'Gespecialiseerd in het vervoer van vloeibare resources. Enorme laadruimte voor grondstoffen als Pyrogel, Aquapure en Bioplasma.',
        prijs: 210000,
        snelheid: 1,
        laadruimte: 220,
        schild: 3,
        kleur: '#6B8E23',
        passagiersCapaciteit: 2,
        brandstofTank: 150,
        maxHP: 90,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_3b',
        type: 'vracht',
        mark: 3,
        specialisatie: 'b',
        naam: 'Secure Hauler Mark III',
        icoon: '🔒',
        beschrijving: 'Gepantserd vrachtschip voor luxe en waardevolle lading. Immuun voor piraten. Mortex-lading wordt nooit geconfisqueerd.',
        prijs: 210000,
        snelheid: 2,
        laadruimte: 130,
        schild: 5,
        kleur: '#4169E1',
        passagiersCapaciteit: 2,
        brandstofTank: 150,
        maxHP: 90,
        immuunPiraten: true,
        immuunMortexConfiscatie: true,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_4a',
        type: 'vracht',
        mark: 4,
        specialisatie: 'a',
        naam: 'Tanker Mark IV',
        icoon: '🛢️',
        beschrijving: 'De ultieme tanker. Monsterlijke laadcapaciteit voor vloeibare grondstoffen. Verplaatst marktprijzen bij aankomst.',
        prijs: 680000,
        snelheid: 2,
        laadruimte: 350,
        schild: 4,
        kleur: '#7BAA2A',
        passagiersCapaciteit: 3,
        brandstofTank: 180,
        maxHP: 120,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_4b',
        type: 'vracht',
        mark: 4,
        specialisatie: 'b',
        naam: 'Secure Hauler Mark IV',
        icoon: '🔒',
        beschrijving: 'Onneembaar pantservrachtschip. Geen enkel gevaar kan je lading bereiken.',
        prijs: 680000,
        snelheid: 2,
        laadruimte: 170,
        schild: 5,
        kleur: '#4A79F1',
        passagiersCapaciteit: 3,
        brandstofTank: 180,
        maxHP: 120,
        immuunPiraten: true,
        immuunMortexConfiscatie: true,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    // === PASSAGIERSSCHIP ===
    {
        id: 'pax_1',
        type: 'pax',
        mark: 1,
        specialisatie: null,
        naam: 'Passagiersschip Mark I',
        icoon: '🛳️',
        beschrijving: 'Comfortabel passagiersschip. Trekt reizigers aan op alle routes met een goed serviceniveau.',
        prijs: 18000,
        snelheid: 2,
        laadruimte: 15,
        schild: 2,
        kleur: '#1E90FF',
        passagiersCapaciteit: 20,
        brandstofTank: 90,
        maxHP: 50,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'pax_2',
        type: 'pax',
        mark: 2,
        specialisatie: null,
        naam: 'Passagiersschip Mark II',
        icoon: '🛳️',
        beschrijving: 'Verbeterd passagiersschip met dubbele capaciteit en comfortabelere inrichting.',
        prijs: 70000,
        snelheid: 2,
        laadruimte: 20,
        schild: 2,
        kleur: '#2EA0FF',
        passagiersCapaciteit: 40,
        brandstofTank: 110,
        maxHP: 65,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'pax_3a',
        type: 'pax',
        mark: 3,
        specialisatie: 'a',
        naam: 'Luxury Liner Mark III',
        icoon: '🥂',
        beschrijving: 'Exclusief luxejacht voor de galactische elite. Minder passagiers, maar zij betalen driemaal de normale ticketprijs.',
        prijs: 220000,
        snelheid: 3,
        laadruimte: 20,
        schild: 3,
        kleur: '#FFD700',
        passagiersCapaciteit: 20,
        brandstofTank: 130,
        maxHP: 85,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 3,
        spearheadBonus: false,
    },
    {
        id: 'pax_3b',
        type: 'pax',
        mark: 3,
        specialisatie: 'b',
        naam: 'Space Bus Mark III',
        icoon: '🚌',
        beschrijving: 'Maximale capaciteit voor massa-transport. Lage ticketprijs trekt grote aantallen passagiers aan.',
        prijs: 220000,
        snelheid: 2,
        laadruimte: 20,
        schild: 2,
        kleur: '#FF8C00',
        passagiersCapaciteit: 80,
        brandstofTank: 130,
        maxHP: 85,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 0.5,
        spearheadBonus: false,
    },
    {
        id: 'pax_4a',
        type: 'pax',
        mark: 4,
        specialisatie: 'a',
        naam: 'Luxury Liner Mark IV',
        icoon: '🥂',
        beschrijving: 'Het summum van galactische luxe. Alleen de rijksten kunnen zich een ticket veroorloven.',
        prijs: 700000,
        snelheid: 3,
        laadruimte: 25,
        schild: 4,
        kleur: '#FFE030',
        passagiersCapaciteit: 24,
        brandstofTank: 150,
        maxHP: 110,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 3,
        spearheadBonus: false,
    },
    {
        id: 'pax_4b',
        type: 'pax',
        mark: 4,
        specialisatie: 'b',
        naam: 'Space Bus Mark IV',
        icoon: '🚌',
        beschrijving: 'De galactische volksvervoerder. Transporteert een halve kolonie per rit.',
        prijs: 700000,
        snelheid: 2,
        laadruimte: 25,
        schild: 2,
        kleur: '#FFA020',
        passagiersCapaciteit: 120,
        brandstofTank: 150,
        maxHP: 110,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 0.5,
        spearheadBonus: false,
    },
    // === SNEL SCHIP ===
    {
        id: 'snel_1',
        type: 'snel',
        mark: 1,
        specialisatie: null,
        naam: 'Snel Schip Mark I',
        icoon: '✈️',
        beschrijving: 'Licht en snel. Kleine laadruimte, maar arriveert eerder dan de concurrentie. Ideaal voor opportunistische handel.',
        prijs: 19000,
        snelheid: 3,
        laadruimte: 20,
        schild: 1,
        kleur: '#FF6B35',
        passagiersCapaciteit: 4,
        brandstofTank: 70,
        maxHP: 45,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_2',
        type: 'snel',
        mark: 2,
        specialisatie: null,
        naam: 'Snel Schip Mark II',
        icoon: '✈️',
        beschrijving: 'Opgewaardeerde snelle courier. Meer laadruimte zonder snelheid in te leveren.',
        prijs: 75000,
        snelheid: 5,
        laadruimte: 30,
        schild: 1,
        kleur: '#FF7B45',
        passagiersCapaciteit: 6,
        brandstofTank: 85,
        maxHP: 60,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_3a',
        type: 'snel',
        mark: 3,
        specialisatie: 'a',
        naam: 'Spearhead Mark III',
        icoon: '⚡',
        beschrijving: 'Snelste schip in de sector. Arriveert altijd vóór de concurrenten en pakt een marktkorting van 8% mee op alle aankoopprijzen.',
        prijs: 235000,
        snelheid: 8,
        laadruimte: 40,
        schild: 2,
        kleur: '#FFD700',
        passagiersCapaciteit: 6,
        brandstofTank: 100,
        maxHP: 75,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: true,
    },
    {
        id: 'snel_3b',
        type: 'snel',
        mark: 3,
        specialisatie: 'b',
        naam: 'Shadow Mark III',
        icoon: '🌑',
        beschrijving: 'Onzichtbaar smokkelschip. Piraten negeren je volledig. Douanekans drastisch verlaagd naar 5%. Perfect voor Mortex-routes.',
        prijs: 235000,
        snelheid: 7,
        laadruimte: 45,
        schild: 1,
        kleur: '#6A0DAD',
        passagiersCapaciteit: 4,
        brandstofTank: 95,
        maxHP: 75,
        immuunPiraten: true,
        immuunMortexConfiscatie: false,
        douaneKansOverride: 0.05,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_4a',
        type: 'snel',
        mark: 4,
        specialisatie: 'a',
        naam: 'Spearhead Mark IV',
        icoon: '⚡',
        beschrijving: 'Ongeëvenaarde snelheid. Geen enkele concurrent arriveert eerder. Maximale marktkorting van 8% gegarandeerd.',
        prijs: 740000,
        snelheid: 10,
        laadruimte: 50,
        schild: 3,
        kleur: '#FFDF20',
        passagiersCapaciteit: 8,
        brandstofTank: 115,
        maxHP: 100,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: true,
    },
    {
        id: 'snel_4b',
        type: 'snel',
        mark: 4,
        specialisatie: 'b',
        naam: 'Shadow Mark IV',
        icoon: '🌑',
        beschrijving: 'Het ultieme spookschip. Radaronzichtbaar, piratenimmuun, douaneonzichtbaar. Beheers de zwarte markt.',
        prijs: 740000,
        snelheid: 9,
        laadruimte: 60,
        schild: 1,
        kleur: '#7A1DBD',
        passagiersCapaciteit: 4,
        brandstofTank: 110,
        maxHP: 100,
        immuunPiraten: true,
        immuunMortexConfiscatie: false,
        douaneKansOverride: 0.05,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
];

const UPGRADES = [];

// Crew-grootte per schip (bemanning vereist voor bediening)
const CREW_PER_SCHIP = {
    vracht_1: 3,  vracht_2: 5,  vracht_3a: 8,  vracht_3b: 7,  vracht_4a: 12, vracht_4b: 10,
    pax_1:    4,  pax_2:    6,  pax_3a:   10,  pax_3b:    7,  pax_4a:   14,  pax_4b:   10,
    snel_1:   2,  snel_2:   3,  snel_3a:   5,  snel_3b:    4,  snel_4a:   7,  snel_4b:    6,
};

// Kansen optellen naar 1.0
const EVENTS = [
    {
        id: 'piraten',
        naam: 'Ruimtepiraten!',
        icoon: '☠️',
        type: 'gevaar',
        kans: 0.10,
        beschrijving: 'Een piratengroep onderschept je schip en blokkeert je route. Ze eisen tol voor veilige doorgang.',
        heeftKeuze: true,
        keuzes: [
            { id: 'betaal', tekst: 'Betaal het losgeld', stijl: 'gevaar' },
            { id: 'vlucht', tekst: 'Probeer te ontsnappen', stijl: 'knop' },
        ],
    },
    {
        id: 'stralingstorm',
        naam: 'Stralingstorm',
        icoon: '⚡',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een zware stralingstorm treft je route. Je moet een grote omweg nemen — dat kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'ruimtewrak',
        naam: 'Ruimtewrak Gevonden',
        icoon: '🛸',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Je detecteert een verlaten handelsschip. Na onderzoek vind je nog bruikbare lading aan boord!',
        heeftKeuze: false,
    },
    {
        id: 'defect',
        naam: 'Mechanisch Defect',
        icoon: '🔧',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een cruciaal onderdeel geeft het op. Je moet halverwege stoppen voor noodreparaties.',
        heeftKeuze: true,
        keuzes: [
            { id: 'repareer', tekst: 'Repareer direct (400 credits)', stijl: 'gevaar' },
            { id: 'doorvaren', tekst: 'Doorvaren met beschadiging', stijl: 'knop' },
        ],
    },
    {
        id: 'smokkelbod',
        naam: 'Sluiksmokkelaar',
        icoon: '🤫',
        type: 'kans',
        kans: 0.07,
        beschrijving: 'Een mysterieuze smokkelaar biedt je goederen aan ver onder de marktprijs. Riskant, maar potentieel winstgevend.',
        heeftKeuze: true,
        keuzes: [
            { id: 'koop', tekst: 'Koop de goederen', stijl: 'succes' },
            { id: 'weiger', tekst: 'Weiger het aanbod', stijl: 'knop' },
        ],
    },
    {
        id: 'nevel',
        naam: 'Ionennevel',
        icoon: '🌫️',
        type: 'neutraal',
        kans: 0.08,
        beschrijving: 'Je vliegt door een dichte ionennevel. Navigatiesystemen raken verstoord — de omweg kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'tip',
        naam: 'Handelstip',
        icoon: '💡',
        type: 'kans',
        kans: 0.09,
        beschrijving: 'Je ontmoet een vriendelijke ruimtekapitein die je een waardevolle tip geeft over de marktprijzen!',
        heeftKeuze: false,
    },
    {
        id: 'asteroiden',
        naam: 'Asteroïdenveld',
        icoon: '🪨',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Je vliegt onverwacht een dicht asteroïdenveld in. Je schip loopt averij op!',
        heeftKeuze: false,
    },
    {
        id: 'douane',
        naam: 'Douanecontrole',
        icoon: '🔍',
        type: 'neutraal',
        kans: 0.07,
        beschrijving: 'Galactische douaniers stoppen je voor een grondige controle. Ze kijken of alles in orde is.',
        heeftKeuze: false,
    },
    {
        id: 'bonus',
        naam: 'Galactische Subsidie',
        icoon: '🎁',
        type: 'kans',
        kans: 0.06,
        beschrijving: 'Gefeliciteerd! Je ontvangt een onverwachte handelssubsidie van de Galactische Handelsgilde!',
        heeftKeuze: false,
    },
    {
        id: 'brandstof_vraag',
        naam: 'Noodoproep: Brandstof',
        icoon: '🆘',
        type: 'neutraal',
        kans: 0.05,
        beschrijving: 'Een gestrande ruimtepiloot roept je via de noodfrequentie op. Ze zit zonder brandstof en vraagt om hulp.',
        heeftKeuze: true,
        keuzes: [
            { id: 'geef', tekst: 'Geef 20 liter brandstof', stijl: 'succes' },
            { id: 'weiger', tekst: 'Vlieg door', stijl: 'knop' },
        ],
    },
    {
        id: 'lifter',
        naam: 'Ruimtelift Gevraagd',
        icoon: '🧳',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Een reiziger wil meelliften naar je bestemming.', // dynamic in UI
        heeftKeuze: true,
        keuzes: [
            { id: 'meenemen', tekst: 'Neem de lifter mee', stijl: 'succes' },
            { id: 'weiger', tekst: 'Rijd door', stijl: 'knop' },
        ],
    },
    {
        id: 'bederf',
        naam: 'Goederen Bedorven!',
        icoon: '🤢',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Door een storing in je koelsysteem zijn een deel van je goederen bedorven. Je verliest de helft!',
        heeftKeuze: false,
    },
    {
        id: 'haven_gesloten',
        naam: 'Ruimtehaven Gesloten',
        icoon: '🚫',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'De ruimtehaven van je bestemming is plotseling gesloten vanwege een quarantaineprotocol. Je moet noodkoers zetten naar de dichtstbijzijnde alternatieve haven.',
        heeftKeuze: false,
    },
    {
        id: 'noodlanding',
        naam: 'Noodlanding',
        icoon: '🆘',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een kritische motorsysteem storing dwingt je tot een noodlanding op de dichtstbijzijnde planeet. Je geplande bestemming is niet meer haalbaar.',
        heeftKeuze: false,
    },
    {
        id: 'douaneboete',
        naam: 'Galactische Douaneboete',
        icoon: '🚨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Douaneinspecteurs leggen een fikse boete op wegens een papierwerk-overtreding. Je moet direct betalen.',
        heeftKeuze: false,
    },
    {
        id: 'cargo_lek',
        naam: 'Containerlek',
        icoon: '💨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Een container heeft een druklek. Kostbare lading is in de ruimte verdwenen voor je het door had.',
        heeftKeuze: false,
    },
    {
        id: 'motordiefstal',
        naam: 'Ruimtediefstal',
        icoon: '🦹',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'Een listige ruimtecrimineel heeft onopgemerkt je vrachtruim doorzocht en credits buitgemaakt.',
        heeftKeuze: false,
    },
    {
        id: 'niets',
        naam: 'Rustige reis',
        icoon: '🌟',
        type: 'neutraal',
        kans: 0.18,
        beschrijving: 'De reis verloopt vlekkeloos. Sterrenbeelden passeren, je koers is recht, en alles is in orde.',
        heeftKeuze: false,
    },
    {
        id: 'crew_opstand',
        naam: 'Crew Opstand!',
        icoon: '✊',
        type: 'gevaar',
        kans: 0,   // Alleen getriggerd door geluk-check; nooit via normale pool
        beschrijving: 'Je bemanning is tot het uiterste gedreven. Ze eisen onmiddellijke betaling, anders leggen ze het werk neer.',
        heeftKeuze: true,
        keuzes: [
            { id: 'betaal', tekst: 'Betaal dubbel salaris', stijl: 'gevaar' },
            { id: 'praten', tekst: 'Onderhandel (50% kans)', stijl: 'knop' },
        ],
    },
    // === BANK EVENTS ===
    {
        id: 'bank_rente_omhoog',
        naam: 'Galactische Monetaire Unie verhoogt basisrente',
        icoon: '🏦',
        type: 'positief',
        kans: 0.04,
        beschrijving: 'De Galactische Monetaire Unie heeft de basisrente verhoogd. Je spaarrente stijgt met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_hoogconjunctuur',
        naam: 'Economische Hoogconjunctuur',
        icoon: '📈',
        type: 'positief',
        kans: 0.03,
        beschrijving: 'Een periode van economische bloei. Alle banken verhogen hun rente tijdelijk met 1%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_kredietexpansie',
        naam: 'Kredietexpansie in de Buitenste Ring',
        icoon: '💹',
        type: 'positief',
        kans: 0.04,
        beschrijving: 'Een nieuwe kredietlijn wordt opengesteld door de Galactische Handelsbank. Spaarrente stijgt met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_recessie',
        naam: 'Intergalactische Recessie Dreigt',
        icoon: '📉',
        type: 'gevaar',
        kans: 0.04,
        beschrijving: 'Economische onzekerheid trekt door de melkweg. Bankrentes dalen met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_nulrente',
        naam: 'Centrale Bank Voert Nulrentebeleid In',
        icoon: '🏛️',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'De Galactische Centrale Bank verlaagt de rente naar nul. Je spaargeld groeit tijdelijk niet meer.',
        heeftKeuze: false,
    },
    {
        id: 'bank_crisis',
        naam: 'Bankcrisis op Nexoria',
        icoon: '⚠️',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'Een bankcrisis heeft de sector geschokt. Spaarrentes worden met 1% verlaagd.',
        heeftKeuze: false,
    },
    {
        id: 'bank_belasting',
        naam: 'Vermogensbelasting Galacticus',
        icoon: '💸',
        type: 'gevaar',
        kans: 0.03,
        beschrijving: 'De Belastingdienst Galacticus vordert 3% van je banksaldo als vermogensbelasting.',
        heeftKeuze: false,
    },
    {
        id: 'bank_bonus',
        naam: 'Spaarbonus-actie',
        icoon: '🎁',
        type: 'positief',
        kans: 0.03,
        beschrijving: 'Als trouwe rekeninghouder ontvang je een eenmalige spaarbonus van 500 credits.',
        heeftKeuze: false,
    },
    {
        id: 'bank_bevriezing',
        naam: 'Bankbevriezing door Politieke Onrust',
        icoon: '🔒',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'Politieke onrust heeft alle banktransacties tijdelijk geblokkeerd. Storten en opnemen is de komende beurt niet mogelijk.',
        heeftKeuze: false,
    },

    // GELD / GELUK
    { id: 'erfenis', naam: 'Verre Erfenis', icoon: '📜', type: 'kans', kans: 0.04, beschrijving: 'Een galactische notaris bereikt je via de noodfrequentie. Een ver familielid heeft je credits nagelaten.', heeftKeuze: false },
    { id: 'loterij', naam: 'Galactische Loterij', icoon: '🎟️', type: 'kans', kans: 0.03, beschrijving: 'Het loterijticket dat je maanden geleden kocht, blijkt een prijs te hebben opgeleverd!', heeftKeuze: false },
    { id: 'keizerlijke_donatie', naam: 'Galactische Smeekbede', icoon: '👑', type: 'gevaar', kans: 0.04, beschrijving: 'De Galactische Kanselier vraagt — in niet mis te verstane bewoordingen — om een "vrijwillige bijdrage" aan het Galactisch Welvaartsfonds. Weigeren heeft gevolgen.', heeftKeuze: true, keuzes: [{ id: 'doneer', tekst: 'Doneer 700 credits', stijl: 'gevaar' }, { id: 'weiger', tekst: 'Weiger vriendelijk', stijl: 'knop' }] },
    { id: 'speculant_bod', naam: 'Ruimtespeculant', icoon: '🤑', type: 'kans', kans: 0.05, beschrijving: 'Een zwevende koopman onderschept je signaal. Hij biedt 115% van de marktwaarde voor al je lading — contant, geen vragen gesteld.', heeftKeuze: true, keuzes: [{ id: 'verkoop', tekst: 'Verkoop alles (115% waarde)', stijl: 'succes' }, { id: 'weiger', tekst: 'Bedankt, maar nee', stijl: 'knop' }] },
    { id: 'belastingboete', naam: 'Galactische Naheffing', icoon: '🧾', type: 'gevaar', kans: 0.05, beschrijving: 'De Galactische Belastingdienst ontdekte een administratieve fout — in hun voordeel. Je ontvangt een naheffingsaanslag van 3% van je credits.', heeftKeuze: false },

    // CARGO
    { id: 'geheime_lading', naam: 'Mysterieus Pakket', icoon: '📦', type: 'kans', kans: 0.04, beschrijving: 'Een naamloze drone koppelt aan je luik en laat een verzegeld krat achter. Geen afzender.', heeftKeuze: true, keuzes: [{ id: 'open', tekst: 'Open het krat', stijl: 'succes' }, { id: 'dump', tekst: 'Dump het de ruimte in', stijl: 'knop' }] },
    { id: 'slechte_kwaliteit', naam: 'Bedorven Lading', icoon: '🤢', type: 'gevaar', kans: 0.05, beschrijving: 'Een bemanningslid ontdekt dat een deel van je organische lading al beschimmeld is bij de bron. Je hebt geen keuze — het overboord ermee.', heeftKeuze: false },
    { id: 'cargo_volledig_verloren', naam: 'Lading Volledig Vernietigd', icoon: '💥', type: 'gevaar', kans: 0.03, beschrijving: 'Door een kortsluiting in de drukregeling overkookt je vrachtruim. Alles wat erin zat is onbruikbaar geworden.', heeftKeuze: false },
    { id: 'smokkelaar_ruil', naam: 'Ruilaanbod van een Smokkelaar', icoon: '🤫', type: 'kans', kans: 0.04, beschrijving: 'Een bekende tussenpersoon biedt een ruilhandel aan: al je lading inleveren voor een kleinere partij hoogwaardige Luxuriet én 500 credits toe.', heeftKeuze: true, keuzes: [{ id: 'ruil', tekst: 'Accepteer de ruil', stijl: 'succes' }, { id: 'weiger', tekst: 'Weiger', stijl: 'knop' }] },
    { id: 'brandstoflek', naam: 'Brandstoflek', icoon: '⛽', type: 'gevaar', kans: 0.05, beschrijving: 'Je ingenieur ontdekt een lek in de hoofdtank. Ze stoppen het snel, maar niet snel genoeg — de helft van je brandstof is al verdwenen.', heeftKeuze: false },

    // SCHIP / HP
    { id: 'kosmische_wolk', naam: 'Corrosieve Gaswolk', icoon: '☁️', type: 'gevaar', kans: 0.05, beschrijving: 'Je schip vliegt door een ongekaarteerde wolk van bijtende deeltjes. De buitenbeplating is aangetast — je schip lijdt scheepschade.', heeftKeuze: false },
    { id: 'ruimtewal', naam: 'Botsing met Ruimtepuin', icoon: '🪨', type: 'gevaar', kans: 0.05, beschrijving: 'Een ongeregistreerde puinwolk op je route. Je ontwijk het grootste deel, maar een flinke klomp treft de romp.', heeftKeuze: true, keuzes: [{ id: 'repareer', tekst: 'Repareer onderweg (500 credits)', stijl: 'gevaar' }, { id: 'doorvaren', tekst: 'Doorvaren met schade', stijl: 'knop' }] },
    { id: 'onderdeel_gevonden', naam: 'Drijvend Scheepsonderdeel', icoon: '🔧', type: 'kans', kans: 0.04, beschrijving: 'Je scanners pikken een bruikbaar onderdeel op uit een verlaten wrak. Na installatie herstelt je schip een deel van zijn capaciteit.', heeftKeuze: true, keuzes: [{ id: 'meenemen', tekst: 'Installeer het (+15 HP)', stijl: 'succes' }, { id: 'negeer', tekst: 'Vlieg door', stijl: 'knop' }] },

    // PASSAGIERS
    { id: 'vip_passagier', naam: 'VIP aan Boord', icoon: '🎩', type: 'kans', kans: 0.05, beschrijving: 'Een galactische zakenman drijft op een noodpod en wil dringend naar je bestemming. Hij betaalt het drievoudige tarief.', heeftKeuze: true, keuzes: [{ id: 'meenemen', tekst: 'Neem hem mee (3× ticket)', stijl: 'succes' }, { id: 'weiger', tekst: 'Geen ruimte', stijl: 'knop' }] },
    { id: 'noodoproep_passagier', naam: 'Noodevacuatie', icoon: '🚨', type: 'neutraal', kans: 0.04, beschrijving: 'Een drijvende reddingscapsule met evacuees onderschept je route. Ze smeken om vervoer naar jouw bestemming. Geen betaling, wel een goed gevoel.', heeftKeuze: true, keuzes: [{ id: 'meenemen', tekst: 'Neem ze mee (gratis)', stijl: 'succes' }, { id: 'weiger', tekst: 'Vlieg door', stijl: 'knop' }] },
    { id: 'passagier_wangedrag', naam: 'Wangedrag aan Boord', icoon: '😠', type: 'gevaar', kans: 0.04, beschrijving: 'Een dronken passagier heeft de lounge kort en klein geslagen. Reparatiekosten zijn voor jouw rekening — en je crew is er niet blij mee.', heeftKeuze: false },

    // CREW
    { id: 'vakbond_kwijtschelding', naam: 'Vakbondsakkoord', icoon: '🤝', type: 'kans', kans: 0.03, beschrijving: 'De Galactische Bemanningsvakbond heeft intern ruzie. Als gebaar van goede wil worden je achterstallige bemanningskosten kwijtgescholden.', heeftKeuze: false },
    { id: 'crew_bonus_event', naam: 'Vrijwillige Crewbonus', icoon: '✨', type: 'kans', kans: 0.04, beschrijving: 'Je crew heeft de afgelopen reis uitzonderlijk hard gewerkt. Je kunt hen nu een vrijwillige bonus uitkeren.', heeftKeuze: true, keuzes: [{ id: 'geef_bonus', tekst: 'Geef bonus (crew × 150 cr)', stijl: 'succes' }, { id: 'niet', tekst: 'Geen bonus dit keer', stijl: 'knop' }] },
    { id: 'vakbond_eis', naam: 'Vakbondseis Onderweg', icoon: '✊', type: 'gevaar', kans: 0.04, beschrijving: 'Halverwege je reis houdt een vakbondsvertegenwoordiger een toespraak in de kantine. De bemanning eist een directe eenmalige uitkering.', heeftKeuze: true, keuzes: [{ id: 'betaal', tekst: 'Betaal eenmalige uitkering (500 cr)', stijl: 'gevaar' }, { id: 'weiger', tekst: 'Weiger — werk gewoon door', stijl: 'knop' }] },

    // BANK / LENING
    { id: 'kredietlimiet_verhoging', naam: 'Verhoogde Kredietlimiet', icoon: '💳', type: 'kans', kans: 0.04, beschrijving: 'De Galactische Bank heeft je kredietgeschiedenis bekeken en besluit je maximale leenbedrag met 2.000 credits te verhogen.', heeftKeuze: false },
    { id: 'schuldeiser', naam: 'Incassobot Onderschept Je', icoon: '🤖', type: 'gevaar', kans: 0.04, beschrijving: 'De Galactische Bank stuurt een incassobot die je onderschept. Ze eisen directe deelbetaling van je schuld, of ze leggen een boeteclausule op.', heeftKeuze: true, keuzes: [{ id: 'betaal', tekst: 'Betaal 25% schuld af', stijl: 'gevaar' }, { id: 'weiger', tekst: 'Weiger (renteboete)', stijl: 'knop' }] },
    { id: 'beurs_insider', naam: 'Beursinformant', icoon: '📊', type: 'kans', kans: 0.04, beschrijving: 'Een anonieme bron fluistert je de naam in van een aandeel dat de komende beurten sterk zal stijgen. Welk aandeel dit is, wordt duidelijk in je logboek.', heeftKeuze: false },
    { id: 'aandelencrash_event', naam: 'Beurscrash', icoon: '📉', type: 'neutraal', kans: 0.03, beschrijving: 'Galactisch nieuws bereikt je: de Beurs op Nexoria heeft een plotse correctie ondergaan. Alle aandelen staan 20% lager.', heeftKeuze: false },

    // CONCURRENT
    { id: 'concurrent_investering', naam: 'Concurrent in Financiële Problemen', icoon: '🏳️', type: 'kans', kans: 0.04, beschrijving: 'Geruchten bereiken je: Makelaar Voss heeft een reeks slechte deals gemaakt. Zijn vermogen is flink gekrompen.', heeftKeuze: false },
    { id: 'concurrent_sabotage', naam: 'Sabotage door Concurrent', icoon: '🦹', type: 'gevaar', kans: 0.04, beschrijving: 'Iemand heeft je brandstoffilters gesaboteerd bij de laatste aanlegplaats. Je verbruikt de rest van de reis extra brandstof.', heeftKeuze: false },
    { id: 'spionagedienst', naam: 'Ruimtespion Te Huur', icoon: '🕶️', type: 'kans', kans: 0.03, beschrijving: 'Een industriespion biedt zijn diensten aan. Als je hem betaalt, saboteert hij één concurrent — hun vermogen krimpt met 10%. Maar als hij gepakt wordt, rolt de boete naar jou.', heeftKeuze: true, keuzes: [{ id: 'inhuren', tekst: 'Inhuren (800 credits, riskant)', stijl: 'gevaar' }, { id: 'weiger', tekst: 'Weiger dit aanbod', stijl: 'knop' }] },

    // MARKETING / VERZEKERING
    { id: 'mond_tot_mond', naam: 'Mond-tot-Mondreclame', icoon: '📣', type: 'kans', kans: 0.04, beschrijving: 'Reizigers spreken lovend over jouw service op de interplanetaire forums. Zonder extra kosten wachten meer passagiers op je bestemming.', heeftKeuze: false },
    { id: 'marketing_sabotage', naam: 'Marketingsabotage', icoon: '📢', type: 'gevaar', kans: 0.03, beschrijving: 'Een concurrent heeft je marketingcampagne onderschept en vervangen door misleidende berichten. Je campagne is tenietgedaan.', heeftKeuze: false },
    { id: 'verzekering_aanbieding', naam: 'Verzekeringsaanbieding', icoon: '🛡️', type: 'kans', kans: 0.04, beschrijving: 'Een verzekeringsagent benadert je tussen twee sterren in. Hij biedt een gratis noodverzekering aan voor deze reis.', heeftKeuze: false },
    { id: 'verzekering_fraude', naam: 'Valse Verzekeraar', icoon: '🎭', type: 'gevaar', kans: 0.03, beschrijving: 'De verzekeraar waarmee je dacht zaken te doen, blijkt een oplichter. Je premie is verdwenen — en je hebt géén dekking.', heeftKeuze: false },
];

const AANDELEN = [
    { id: 'nexcorp',    naam: 'NexCorp Mining',    icoon: '⛏️', basisPrijs: 100, beschrijving: 'Mijnbouwconglomeraat actief op Ferrum' },
    { id: 'aquatech',   naam: 'AquaTech',           icoon: '💧', basisPrijs: 75,  beschrijving: 'Waterbehandeling en distributie' },
    { id: 'pyroenergie',naam: 'PyroEnergie NV',     icoon: '⚡', basisPrijs: 110, beschrijving: 'Brandstofproducent op Pyroflux' },
    { id: 'luxtrading', naam: 'LuxTrading Corp',    icoon: '💰', basisPrijs: 180, beschrijving: 'Premium luxehandel gericht op Luxoria' },
    { id: 'techstar',   naam: 'TechStar Industries',icoon: '🌟', basisPrijs: 140, beschrijving: 'Technologiepionier en innovator' },
    { id: 'biomed',     naam: 'BioMed Galax',       icoon: '💊', basisPrijs: 85,  beschrijving: 'Farmaceutisch concern met basis op Aqueron' },
];

const CONCURRENTEN = [
    {
        id: 'zax',
        naam: 'Handelaar Zax',
        icoon: '🦊',
        persoonlijkheid: 'Opportunist',
        beschrijving: 'Een nietsontziende opkoper die elke kans aangrijpt. Snel, gretig, en overal tegelijk aanwezig.',
        snelheid: 3,
        kleur: '#ff6b35',
        startKrediet: 4500,
        baseWinstPerBeurt: 900,
        volatiliteit: 0.13,
    },
    {
        id: 'mira',
        naam: 'Koopman Mira',
        icoon: '💼',
        persoonlijkheid: 'Strateeg',
        beschrijving: 'Berekend en gedisciplineerd. Mira plant elke zet en maakt zelden een fout — de gevaarlijkste concurrent.',
        snelheid: 2,
        kleur: '#00d4ff',
        startKrediet: 5500,
        baseWinstPerBeurt: 1100,
        volatiliteit: 0.05,
    },
    {
        id: 'rok',
        naam: 'Kapitein Rok',
        icoon: '⚡',
        persoonlijkheid: 'Avonturier',
        beschrijving: 'Onstuimig en razendsnel. Rok pikt de beste deals weg voor jij ze ziet, maar maakt ook spectaculaire missers.',
        snelheid: 4,
        kleur: '#ffd700',
        startKrediet: 3000,
        baseWinstPerBeurt: 850,
        volatiliteit: 0.10,
    },
    {
        id: 'voss',
        naam: 'Makelaar Voss',
        icoon: '🎩',
        persoonlijkheid: 'Veteraan',
        beschrijving: 'De oude reus van de handelswereld. Traag, maar zijn netwerk en ervaring leveren hem altijd een voordeel op.',
        snelheid: 1,
        kleur: '#9b59ff',
        startKrediet: 7000,
        baseWinstPerBeurt: 800,
        volatiliteit: 0.04,
    },
    {
        id: 'nyx',
        naam: 'Schaduw Nyx',
        icoon: '🕶️',
        persoonlijkheid: 'Mysterie',
        beschrijving: 'Niemand weet precies wat Nyx doet. Zijn vermogen fluctueert wild — soms verdwijnt het plots, soms verveelvoudigt het.',
        snelheid: 3,
        kleur: '#ff3855',
        startKrediet: 5000,
        baseWinstPerBeurt: 600,
        volatiliteit: 0.22,
    },
];

const ACHIEVEMENTS = [
    {
        id: 'eerste_deal',
        naam: 'Eerste Deal',
        icoon: '🤝',
        categorie: 'deals',
        beschrijving: 'Verkoop voor de eerste keer goederen.',
        beloning: 250,
        check: s => (s.statistieken.verkopen ?? 0) >= 1,
    },
    {
        id: 'tiental',
        naam: 'Actieve Handelaar',
        icoon: '📊',
        categorie: 'deals',
        beschrijving: 'Voltooi 10 handelstransacties.',
        beloning: 750,
        check: s => s.statistieken.handelstransacties >= 10,
    },
    {
        id: 'vijftig',
        naam: 'Handelsmagnaat',
        icoon: '🏪',
        categorie: 'deals',
        beschrijving: 'Voltooi 50 handelstransacties.',
        beloning: 3000,
        check: s => s.statistieken.handelstransacties >= 50,
    },
    {
        id: 'rijkaard',
        naam: 'Rijkaard',
        icoon: '💰',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 10.000 credits.',
        beloning: 1500,
        check: s => s.statistieken.gereisd >= 1 && s.berekenNettowaarde() >= 10000,
    },
    {
        id: 'groot_handelaar',
        naam: 'Groot Handelaar',
        icoon: '🏛️',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 100.000 credits.',
        beloning: 7500,
        check: s => s.statistieken.gereisd >= 1 && s.berekenNettowaarde() >= 100000,
    },
    {
        id: 'millionair',
        naam: 'Galactische Millionair',
        icoon: '🌟',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 1.000.000 credits.',
        beloning: 50000,
        check: s => s.statistieken.gereisd >= 1 && s.berekenNettowaarde() >= 1000000,
    },
    {
        id: 'wereldreiziger',
        naam: 'Wereldreiziger',
        icoon: '🗺️',
        categorie: 'events',
        beschrijving: 'Bezoek alle 8 planeten.',
        beloning: 5000,
        check: s => s.bezochteplaneten && s.bezochteplaneten.size >= 8,
    },
    // Gazillionair
    {
        id: 'gazillionair',
        naam: 'Gazillionair',
        icoon: '🤑',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 25 miljoen credits.',
        beloning: 100000,
        check: s => s.statistieken.gereisd >= 1 && s.berekenNettowaarde() >= 25000000,
    },
    // Schip — Vrachtschip
    {
        id: 'vracht_mark2',
        naam: 'Zware Vrachter',
        icoon: '🚛',
        categorie: 'schip',
        beschrijving: 'Vrachtschip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['vracht_2','vracht_3a','vracht_3b','vracht_4a','vracht_4b'].includes(s.schip?.id),
    },
    {
        id: 'tanker_mark3',
        naam: 'Vloeibare Goudader',
        icoon: '🛢️',
        categorie: 'schip',
        beschrijving: 'Tanker Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['vracht_3a','vracht_4a'].includes(s.schip?.id),
    },
    {
        id: 'secure_mark3',
        naam: 'Onaantastbaar',
        icoon: '🔒',
        categorie: 'schip',
        beschrijving: 'Secure Hauler Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['vracht_3b','vracht_4b'].includes(s.schip?.id),
    },
    {
        id: 'tanker_mark4',
        naam: 'Galactisch Tankschip',
        icoon: '🌊',
        categorie: 'schip',
        beschrijving: 'Tanker Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'vracht_4a',
    },
    {
        id: 'secure_mark4',
        naam: 'Fort Knox',
        icoon: '🏰',
        categorie: 'schip',
        beschrijving: 'Secure Hauler Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'vracht_4b',
    },
    // Schip — Passagiersschip
    {
        id: 'pax_mark2',
        naam: 'Ruimtevervoer',
        icoon: '🛳️',
        categorie: 'schip',
        beschrijving: 'Passagiersschip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['pax_2','pax_3a','pax_3b','pax_4a','pax_4b'].includes(s.schip?.id),
    },
    {
        id: 'luxury_mark3',
        naam: 'Ruimte-elite',
        icoon: '🥂',
        categorie: 'schip',
        beschrijving: 'Luxury Liner Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['pax_3a','pax_4a'].includes(s.schip?.id),
    },
    {
        id: 'spacebus_mark3',
        naam: 'Ruimtetaxi',
        icoon: '🚌',
        categorie: 'schip',
        beschrijving: 'Space Bus Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['pax_3b','pax_4b'].includes(s.schip?.id),
    },
    {
        id: 'luxury_mark4',
        naam: 'Galactische Luxe',
        icoon: '✨',
        categorie: 'schip',
        beschrijving: 'Luxury Liner Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'pax_4a',
    },
    {
        id: 'spacebus_mark4',
        naam: 'Galactische Bus',
        icoon: '🌌',
        categorie: 'schip',
        beschrijving: 'Space Bus Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'pax_4b',
    },
    // Schip — Snel Schip
    {
        id: 'snel_mark2',
        naam: 'Ruimteraket',
        icoon: '🚀',
        categorie: 'schip',
        beschrijving: 'Snel Schip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['snel_2','snel_3a','snel_3b','snel_4a','snel_4b'].includes(s.schip?.id),
    },
    {
        id: 'spearhead_mark3',
        naam: 'Altijd Als Eerste',
        icoon: '⚡',
        categorie: 'schip',
        beschrijving: 'Spearhead Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['snel_3a','snel_4a'].includes(s.schip?.id),
    },
    {
        id: 'shadow_mark3',
        naam: 'Schaduwhandelaar',
        icoon: '🌑',
        categorie: 'schip',
        beschrijving: 'Shadow Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['snel_3b','snel_4b'].includes(s.schip?.id),
    },
    {
        id: 'spearhead_mark4',
        naam: 'Snelste van de Sector',
        icoon: '⚡',
        categorie: 'schip',
        beschrijving: 'Spearhead Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'snel_4a',
    },
    {
        id: 'shadow_mark4',
        naam: 'Ongrijpbaar',
        icoon: '🌑',
        categorie: 'schip',
        beschrijving: 'Shadow Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'snel_4b',
    },
    // Beurs
    {
        id: 'beurs_goeroe',
        naam: 'Beursgoeroe',
        icoon: '📈',
        categorie: 'beurs',
        beschrijving: 'Bezit 4 of meer verschillende aandelen tegelijk.',
        beloning: 2500,
        check: s => Object.values(s.aandelenPortefeuille).filter(v => v > 0).length >= 4,
    },
    {
        id: 'beurs_winst_1k',
        naam: 'Beurswinst',
        icoon: '💹',
        categorie: 'beurs',
        beschrijving: 'Maak 1.000 credits winst op één aandelenverkoop.',
        beloning: 1000,
        check: s => (s._beursBesteDeal ?? 0) >= 1000,
    },
    {
        id: 'beurs_winst_10k',
        naam: 'Beursmagnaat',
        icoon: '🏦',
        categorie: 'beurs',
        beschrijving: 'Maak 10.000 credits winst op één aandelenverkoop.',
        beloning: 5000,
        check: s => (s._beursBesteDeal ?? 0) >= 10000,
    },
    {
        id: 'beurs_totaal_25k',
        naam: 'Beursspeculant',
        icoon: '📊',
        categorie: 'beurs',
        beschrijving: 'Verdien 25.000 credits totaal via aandelenverkoop.',
        beloning: 3000,
        check: s => (s._beursWinstTotaal ?? 0) >= 25000,
    },
    {
        id: 'beurs_totaal_250k',
        naam: 'Galactisch Belegger',
        icoon: '🌟',
        categorie: 'beurs',
        beschrijving: 'Verdien 250.000 credits totaal via aandelenverkoop.',
        beloning: 20000,
        check: s => (s._beursWinstTotaal ?? 0) >= 250000,
    },
    // Handel
    {
        id: 'winstmaker',
        naam: 'Winstmaker',
        icoon: '💎',
        categorie: 'deals',
        beschrijving: 'Maak 5.000 credits winst op één deal.',
        beloning: 1500,
        check: s => s._laatsteWinst >= 5000,
    },
    {
        id: 'superdeal',
        naam: 'Superdeal',
        icoon: '🏆',
        categorie: 'deals',
        beschrijving: 'Maak 25.000 credits winst op één deal.',
        beloning: 5000,
        check: s => s._laatsteWinst >= 25000,
    },
    {
        id: 'reiziger',
        naam: 'Ruimtereiziger',
        icoon: '🚀',
        categorie: 'events',
        beschrijving: 'Maak 10 ruimtereizen.',
        beloning: 1500,
        check: s => s.statistieken.gereisd >= 10,
    },
    {
        id: 'schuldenvrij',
        naam: 'Schuldenvrij',
        icoon: '✅',
        categorie: 'nettowaarde',
        beschrijving: 'Betaal een lening volledig af.',
        beloning: 2000,
        check: s => s._oitLeningGehad && s.speler.schuld === 0,
    },
    {
        id: 'overlever',
        naam: 'Piratenontkomer',
        icoon: '⚡',
        categorie: 'events',
        beschrijving: 'Ontsnapt aan piraten.',
        beloning: 1000,
        check: s => s._piratenOntkomingen > 0,
    },
    {
        id: 'bijna_leeg',
        naam: 'Op de Rand',
        icoon: '⛽',
        categorie: 'events',
        beschrijving: 'Kom aan op een planeet met minder dan 10 liter brandstof.',
        beloning: 300,
        check: s => s._aangekomendMetLageBrandstof,
    },
    {
        id: 'eerste_passagier',
        naam: 'Taxiservice',
        icoon: '🧳',
        categorie: 'events',
        beschrijving: 'Lever je eerste passagier af op zijn bestemming.',
        beloning: 600,
        check: s => s.statistieken.passagiersAfgeleverd >= 1,
    },
    {
        id: 'veilingmeester',
        naam: 'Veilingmeester',
        icoon: '🔨',
        categorie: 'events',
        beschrijving: 'Win een oogstveiling op Agria.',
        beloning: 1000,
        check: s => (s.statistieken.veilingenGewonnen ?? 0) >= 1,
    },
    {
        id: 'alchemist',
        naam: 'Alchemist',
        icoon: '🧪',
        categorie: 'schip',
        beschrijving: 'Verwerk in totaal 30 ton Ferroiet in de ertsverwerkingsfaciliteit op Ferrum.',
        beloning: 1500,
        check: s => (s.statistieken.ferroietVerwerkt ?? 0) >= 30,
    },
    {
        id: 'energieboer',
        naam: 'Energieboer',
        icoon: '⚡',
        categorie: 'reizen',
        beschrijving: 'Tank 10× op het Energiedepot van Pyroflux.',
        beloning: 600,
        check: s => (s.statistieken.pyrofluxTankbeurten ?? 0) >= 10,
    },
    {
        id: 'huisvoordeel',
        naam: 'Huisvoordeel',
        icoon: '🃏',
        categorie: 'events',
        beschrijving: 'Win 3× op rij in het Casino Stellaris op Luxoria.',
        beloning: 1200,
        check: s => (s.statistieken.casinoWinstStreak ?? 0) >= 3,
    },
    {
        id: 'jackpot',
        naam: 'Jackpot',
        icoon: '🎰',
        categorie: 'events',
        beschrijving: 'Win 3.000+ credits in één gokbeurt.',
        beloning: 2500,
        check: s => (s.statistieken.casinoBigWin ?? 0) >= 1,
    },
    {
        id: 'zwarthandelaar',
        naam: 'Zwarthandelaar',
        icoon: '🕵️',
        categorie: 'handel',
        beschrijving: 'Vervoer verdachte lading van Mortex zonder gepakt te worden.',
        beloning: 1000,
        check: s => (s.statistieken.mortexGladGestreken ?? 0) >= 1,
    },
    {
        id: 'bank_100k',
        naam: 'Stevige Spaarpot',
        icoon: '🏦',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 100.000 credits.',
        beloning: 5000,
        check: s => (s.bankSaldo ?? 0) >= 100000,
    },
    {
        id: 'bank_250k',
        naam: 'Galactisch Vermogen',
        icoon: '💰',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 250.000 credits.',
        beloning: 10000,
        check: s => (s.bankSaldo ?? 0) >= 250000,
    },
    {
        id: 'bank_500k',
        naam: 'Ruimtebankier',
        icoon: '💎',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 500.000 credits.',
        beloning: 25000,
        check: s => (s.bankSaldo ?? 0) >= 500000,
    },
];

// =============================================================================
// MISSIES — Opdrachtenbord per planeet
// =============================================================================

const MISSIES = [

    // =========================================================================
    // AQUERON
    // =========================================================================
    {
        id: 'aq_medische_supplies',
        planeet: 'aqueron',
        naam: 'Medische Noodleverantie',
        icoon: '💊',
        beschrijving: 'Het medisch centrum op Aqueron heeft dringend bioplasma nodig voor operaties. Reguliere aanvoer is uitgevallen.',
        type: 'levering',
        vereistGoed: 'bioplasma',
        vereistHoeveelheid: 8,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 5000,
        boeteCredits: 1200,
        deadlineBeurten: 1,
        kans: 0.75,
        categorie: 'spoed',
    },
    {
        id: 'aq_specialist_transport',
        planeet: 'aqueron',
        naam: 'Medisch Specialist Gevraagd',
        icoon: '🧬',
        beschrijving: 'Een medisch specialist moet met spoed naar [bestemming]. Geen regulier medisch transport beschikbaar — jij bent de enige optie.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 1,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 5600,
        boeteCredits: 1600,
        deadlineBeurten: 1,
        kans: 0.65,
        categorie: 'spoed',
    },
    {
        id: 'aq_technoware_apparatuur',
        planeet: 'aqueron',
        naam: 'Laboratoriumapparatuur Besteld',
        icoon: '🔌',
        beschrijving: 'Het biotech-lab op Aqueron wacht op een levering technoware voor nieuwe onderzoeksapparatuur. Bestelling staat al weken open.',
        type: 'levering',
        vereistGoed: 'technoware',
        vereistHoeveelheid: 10,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 2200,
        boeteCredits: 500,
        deadlineBeurten: 5,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'aq_quantumchips_lab',
        planeet: 'aqueron',
        naam: 'Quantumchips voor Diagnostiek',
        icoon: '💾',
        beschrijving: 'De diagnostische systemen van het oceaanlab zijn verouderd. Quantumchips zijn besteld maar de leverancier is gevallen — breng ze zelf.',
        type: 'levering',
        vereistGoed: 'quantumchips',
        vereistHoeveelheid: 5,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 3500,
        boeteCredits: 800,
        deadlineBeurten: 5,
        kans: 0.55,
        categorie: 'levering',
    },

    // =========================================================================
    // FERRUM
    // =========================================================================
    {
        id: 'fe_aquapure_bevoorrading',
        planeet: 'ferrum',
        naam: 'Watergebrek op Ferrum',
        icoon: '💧',
        beschrijving: 'De waterrecyclers in mijndistrict 7 zijn uitgevallen. Zonder aanvoer van aquapure houden de arbeiders het niet vol.',
        type: 'levering',
        vereistGoed: 'aquapure',
        vereistHoeveelheid: 15,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'ferrum',
        beloningCredits: 3500,
        boeteCredits: 900,
        deadlineBeurten: 1,
        kans: 0.75,
        categorie: 'spoed',
    },
    {
        id: 'fe_gewonden_aqueron',
        planeet: 'ferrum',
        naam: 'Gewonde Mijnwerkers — Spoed',
        icoon: '🚑',
        beschrijving: 'Explosie in schacht 4. Drie mijnwerkers zijn zwaargewond en moeten met spoed naar het medisch centrum op Aqueron.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 3,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 8000,
        boeteCredits: 2000,
        deadlineBeurten: 1,
        kans: 0.60,
        categorie: 'spoed',
    },
    {
        id: 'fe_kristalliet_generatoren',
        planeet: 'ferrum',
        naam: 'Generatoren Zonder Stroom',
        icoon: '💠',
        beschrijving: 'De energiegeneratoren in de hoofdmijn draaien op reserve. Kristalliet is nodig om ze weer op volle kracht te krijgen.',
        type: 'levering',
        vereistGoed: 'kristalliet',
        vereistHoeveelheid: 12,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'ferrum',
        beloningCredits: 2600,
        boeteCredits: 600,
        deadlineBeurten: 5,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'fe_bijzonder_kristal',
        planeet: 'ferrum',
        naam: 'Bijzonder Kristal — Techton Onderzoek',
        icoon: '🔬',
        beschrijving: 'Mijnwerkers hebben een onbekend kristal opgegraven. Techton-wetenschappers willen het analyseren. Breng het voorzichtig over.',
        type: 'ophalen',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'prototype',
        missieLadingNaam: 'Onbekend kristal',
        missieLadingIcoon: '💎',
        isVerdacht: false,
        ophaalPlaneet: 'ferrum',
        bestemming: 'techton',
        beloningCredits: 3800,
        boeteCredits: 900,
        deadlineBeurten: 6,
        kans: 0.50,
        categorie: 'onderzoek',
    },
    {
        id: 'fe_nebulakorrels_voedsel',
        planeet: 'ferrum',
        naam: 'Voedselvoorraad Opraken',
        icoon: '🌾',
        beschrijving: 'De mijnkolonie heeft de voedselreserves verbruikt. Nebulakorrels zijn besteld — zorg dat ze er op tijd zijn.',
        type: 'levering',
        vereistGoed: 'nebulakorrels',
        vereistHoeveelheid: 20,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'ferrum',
        beloningCredits: 1800,
        boeteCredits: 400,
        deadlineBeurten: 5,
        kans: 0.70,
        categorie: 'levering',
    },

    // =========================================================================
    // AGRIA
    // =========================================================================
    {
        id: 'ag_technoware_machines',
        planeet: 'agria',
        naam: 'Oogstmachines Defect',
        icoon: '🔌',
        beschrijving: 'Drie oogstcombines staan stil door een softwaredefect. Technoware voor de reparatie is dringend nodig vóór het oogstseizoen.',
        type: 'levering',
        vereistGoed: 'technoware',
        vereistHoeveelheid: 10,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'agria',
        beloningCredits: 2400,
        boeteCredits: 600,
        deadlineBeurten: 5,
        kans: 0.75,
        categorie: 'levering',
    },
    {
        id: 'ag_quantumchips_irrigatie',
        planeet: 'agria',
        naam: 'Irrigatiesysteem Upgrade',
        icoon: '💾',
        beschrijving: 'Het nieuwe geautomatiseerde irrigatiesysteem wacht op quantumchips. Zonder upgrade dreigt de oogst te mislukken door droogte.',
        type: 'levering',
        vereistGoed: 'quantumchips',
        vereistHoeveelheid: 4,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'agria',
        beloningCredits: 3200,
        boeteCredits: 750,
        deadlineBeurten: 5,
        kans: 0.60,
        categorie: 'levering',
    },
    {
        id: 'ag_voedselnoodpakketten',
        planeet: 'agria',
        naam: 'Voedselnoodpakketten Gevraagd',
        icoon: '📦',
        beschrijving: 'Na een mislukte oogst op [bestemming] is er een humanitaire nood. Agria stuurt nebulakorrels — jij brengt ze.',
        type: 'levering',
        vereistGoed: 'nebulakorrels',
        vereistHoeveelheid: 25,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 2000,
        boeteCredits: 500,
        deadlineBeurten: 5,
        kans: 0.65,
        categorie: 'levering',
    },
    {
        id: 'ag_mestongeluk_aqueron',
        planeet: 'agria',
        naam: 'Ongeluk op het Veld — Spoed',
        icoon: '🚑',
        beschrijving: 'Bij een pesticideongeval zijn vier landarbeiders onwel geworden. Ze moeten onmiddellijk naar het medisch centrum op Aqueron.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 4,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 7500,
        boeteCredits: 1900,
        deadlineBeurten: 1,
        kans: 0.55,
        categorie: 'spoed',
    },

    // =========================================================================
    // PYROFLUX
    // =========================================================================
    {
        id: 'py_brandstof_noodvoorraad',
        planeet: 'pyroflux',
        naam: 'Brandstofnoodvoorraad Gevraagd',
        icoon: '⛽',
        beschrijving: '[bestemming] zit zonder brandstof na een aanvoerstoring. Pyroflux stuurt een noodlading pyrogel — jij transporteert.',
        type: 'levering',
        vereistGoed: 'pyrogel',
        vereistHoeveelheid: 20,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 2600,
        boeteCredits: 650,
        deadlineBeurten: 4,
        kans: 0.75,
        categorie: 'levering',
    },
    {
        id: 'py_aquapure_koeling',
        planeet: 'pyroflux',
        naam: 'Koelwatertekort Raffinaderij',
        icoon: '💧',
        beschrijving: 'De koelsystemen van de pyrogel-raffinaderij draaien op minimum. Zonder aquapure riskeert men een reactoroverdruk.',
        type: 'levering',
        vereistGoed: 'aquapure',
        vereistHoeveelheid: 18,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'pyroflux',
        beloningCredits: 5000,
        boeteCredits: 1200,
        deadlineBeurten: 1,
        kans: 0.70,
        categorie: 'spoed',
    },
    {
        id: 'py_technoware_stabilisatoren',
        planeet: 'pyroflux',
        naam: 'Reactorstabilisatoren Nodig',
        icoon: '🔌',
        beschrijving: 'Ingenieur Vrak meldt dat de stabilisatoren van reactor 3 het begeven. Technoware reserveonderdelen zijn dringend nodig.',
        type: 'levering',
        vereistGoed: 'technoware',
        vereistHoeveelheid: 8,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'pyroflux',
        beloningCredits: 5500,
        boeteCredits: 1300,
        deadlineBeurten: 1,
        kans: 0.65,
        categorie: 'spoed',
    },
    {
        id: 'py_ingenieur_evacuatie',
        planeet: 'pyroflux',
        naam: 'Evacuatie Raffinaderijpersoneel',
        icoon: '🚒',
        beschrijving: 'Een lavastoringzone breidt zich uit. Vijf ingenieurs moeten met spoed worden geëvacueerd naar Aqueron voor medische controle.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 5,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'aqueron',
        beloningCredits: 9000,
        boeteCredits: 2200,
        deadlineBeurten: 1,
        kans: 0.50,
        categorie: 'spoed',
    },

    // =========================================================================
    // TECHTON
    // =========================================================================
    {
        id: 'te_quantumchips_nexoria',
        planeet: 'techton',
        naam: 'Nieuwe Chips voor de Beurs',
        icoon: '📈',
        beschrijving: 'Techton heeft geavanceerde quantumchips ontwikkeld die beurshandelingen op Nexoria drastisch versnellen. Lever ze persoonlijk af — te waardevol voor reguliere vracht.',
        type: 'levering',
        vereistGoed: 'quantumchips',
        vereistHoeveelheid: 6,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'nexoria',
        beloningCredits: 5500,
        boeteCredits: 1400,
        deadlineBeurten: 5,
        kans: 0.60,
        categorie: 'levering',
    },
    {
        id: 'te_technoware_reserveonderdelen',
        planeet: 'techton',
        naam: 'Reserveonderdelen Uitbesteed',
        icoon: '🔧',
        beschrijving: 'Een productiefaciliteit op [bestemming] wacht op technoware reserveonderdelen. Techton kan niet zelf leveren — te druk met orders.',
        type: 'levering',
        vereistGoed: 'technoware',
        vereistHoeveelheid: 12,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 2400,
        boeteCredits: 600,
        deadlineBeurten: 5,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'te_wetenschappers_field',
        planeet: 'techton',
        naam: 'Fieldresearch Expeditie',
        icoon: '🧪',
        beschrijving: 'Twee Techton-wetenschappers moeten naar [bestemming] voor veldonderzoek. Commerciële vluchten zijn vol — kan jij ze brengen?',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 2,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 3000,
        boeteCredits: 700,
        deadlineBeurten: 5,
        kans: 0.65,
        categorie: 'transport',
    },
    {
        id: 'te_prototype_ophalen',
        planeet: 'techton',
        naam: 'Prototype Ophalen van Ferrum',
        icoon: '📡',
        beschrijving: 'Een waardevolle prototype-module is achtergebleven op Ferrum na een testmissie. Haal hem op en breng hem terug naar Techton.',
        type: 'ophalen',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'prototype',
        missieLadingNaam: 'Prototype module',
        missieLadingIcoon: '📡',
        isVerdacht: false,
        ophaalPlaneet: 'ferrum',
        bestemming: 'techton',
        beloningCredits: 4000,
        boeteCredits: 1000,
        deadlineBeurten: 6,
        kans: 0.50,
        categorie: 'onderzoek',
    },

    // =========================================================================
    // NEXORIA
    // =========================================================================
    {
        id: 'nx_diplomatieke_koeriersdienst',
        planeet: 'nexoria',
        naam: 'Diplomatieke Koeriersdienst',
        icoon: '📜',
        beschrijving: 'De Galactische Handelsgilde heeft vertrouwelijke handelsdocumenten die veilig naar [bestemming] moeten. Geen reguliere vracht — te gevoelig.',
        type: 'levering',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'documenten',
        missieLadingNaam: 'Vertrouwelijke documenten',
        missieLadingIcoon: '📜',
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 2800,
        boeteCredits: 700,
        deadlineBeurten: 4,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'nx_beursinspecteur',
        planeet: 'nexoria',
        naam: 'Beursinspecteur naar Techton',
        icoon: '🏛️',
        beschrijving: 'Een beursinspecteur van de Galactische Monetaire Unie moet dringend naar Techton voor een financiële audit. Zijn eigen shuttle is in onderhoud.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 1,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'techton',
        beloningCredits: 2600,
        boeteCredits: 650,
        deadlineBeurten: 4,
        kans: 0.65,
        categorie: 'transport',
    },
    {
        id: 'nx_noodtransport_valuta',
        planeet: 'nexoria',
        naam: 'Noodtransport Kredietmodules',
        icoon: '💳',
        beschrijving: 'Een planeet in financiële crisis heeft fysieke kredietmodules nodig om de lokale economie draaiende te houden. De bank vraagt jou dit te verzorgen.',
        type: 'levering',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'kredietmodules',
        missieLadingNaam: 'Kredietmodules',
        missieLadingIcoon: '💳',
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 3500,
        boeteCredits: 900,
        deadlineBeurten: 4,
        kans: 0.60,
        categorie: 'levering',
    },
    {
        id: 'nx_handelsdelegatie',
        planeet: 'nexoria',
        naam: 'Handelsdelegatie Vervoeren',
        icoon: '🤝',
        beschrijving: 'Een delegatie van drie Nexoria-handelaren moet naar [bestemming] voor onderhandelingen. Ze betalen goed — maar verwachten stiptheid.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 3,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 3800,
        boeteCredits: 950,
        deadlineBeurten: 4,
        kans: 0.60,
        categorie: 'transport',
    },

    // =========================================================================
    // LUXORIA
    // =========================================================================
    {
        id: 'lx_technoware_casino',
        planeet: 'luxoria',
        naam: 'Nieuwe Geldtelmachines Casino',
        icoon: '🎰',
        beschrijving: 'Casino Stellaris wacht op technoware voor zijn nieuwe geldtelmachines. De directeur is bereid goed te betalen voor snelle levering.',
        type: 'levering',
        vereistGoed: 'technoware',
        vereistHoeveelheid: 8,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'luxoria',
        beloningCredits: 3200,
        boeteCredits: 800,
        deadlineBeurten: 5,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'lx_vip_ophalen',
        planeet: 'luxoria',
        naam: 'VIP-gast Ophalen',
        icoon: '🥂',
        beschrijving: 'Een galactische celebrity moet worden opgehaald van [ophaalPlaneet] voor een exclusief evenement op Luxoria. Discretie vereist.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 1,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'luxoria',
        beloningCredits: 5500,
        boeteCredits: 1400,
        deadlineBeurten: 4,
        kans: 0.55,
        categorie: 'transport',
    },
    {
        id: 'lx_zeldzame_ingredienten',
        planeet: 'luxoria',
        naam: 'Ingrediënten voor het Galadiner',
        icoon: '🍽️',
        beschrijving: 'De privéchef van Grand Resort Stellaris heeft nebulakorrels van topkwaliteit nodig voor het jaarlijkse galadiner. Reguliere leverancier heeft afgezegd.',
        type: 'levering',
        vereistGoed: 'nebulakorrels',
        vereistHoeveelheid: 10,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: null,
        bestemming: 'luxoria',
        beloningCredits: 2200,
        boeteCredits: 550,
        deadlineBeurten: 5,
        kans: 0.65,
        categorie: 'levering',
    },
    {
        id: 'lx_gestolen_kunstobject',
        planeet: 'luxoria',
        naam: 'Gestolen Kunstobject Terugbrengen',
        icoon: '🏺',
        beschrijving: 'Een zeldzaam kunstobject is opgespoord op Mortex. De eigenaar op Luxoria betaalt fors voor terugbezorging — geen vragen gesteld.',
        type: 'ophalen',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'kunstobject',
        missieLadingNaam: 'Gestolen kunstobject',
        missieLadingIcoon: '🏺',
        isVerdacht: true,
        ophaalPlaneet: 'mortex',
        bestemming: 'luxoria',
        beloningCredits: 7000,
        boeteCredits: 1800,
        deadlineBeurten: 6,
        kans: 0.45,
        categorie: 'onderzoek',
    },
    {
        id: 'lx_lunasteen_levering',
        planeet: 'luxoria',
        naam: 'Bijzondere Edelstenen Besteld',
        icoon: '💎',
        beschrijving: 'Een exclusieve juwelier op Luxoria wacht op een partij lunasteen. De leverancier op Ferrum heeft ze klaarliggen — maar niemand brengt ze.',
        type: 'ophalen',
        vereistGoed: 'lunasteen',
        vereistHoeveelheid: 5,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: false,
        ophaalPlaneet: 'ferrum',
        bestemming: 'luxoria',
        beloningCredits: 4800,
        boeteCredits: 1200,
        deadlineBeurten: 6,
        kans: 0.55,
        categorie: 'levering',
    },

    // =========================================================================
    // MORTEX STATION
    // =========================================================================
    {
        id: 'mo_anoniem_pakket',
        planeet: 'mortex',
        naam: 'Anonieme Zending',
        icoon: '📦',
        beschrijving: 'Een onbekende opdrachtgever wil een verzegeld pakket bezorgd hebben op [bestemming]. Inhoud onbekend. Geen vragen stellen. Betaling vooraf.',
        type: 'levering',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'pakket',
        missieLadingNaam: 'Verzegeld pakket',
        missieLadingIcoon: '📦',
        isVerdacht: true,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 6000,
        boeteCredits: 0,
        deadlineBeurten: 4,
        kans: 0.70,
        categorie: 'levering',
    },
    {
        id: 'mo_vluchteling',
        planeet: 'mortex',
        naam: 'Iemand Wil Hier Weg',
        icoon: '🧳',
        beschrijving: 'Een man vraagt je hem te vervoeren naar [bestemming]. Hij zegt niet waarom hij weg moet — maar het is duidelijk dat hij haast heeft en niet wil worden gezien.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 1,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: true,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 4500,
        boeteCredits: 0,
        deadlineBeurten: 3,
        kans: 0.65,
        categorie: 'transport',
    },
    {
        id: 'mo_verloren_lading',
        planeet: 'mortex',
        naam: '"Gevonden" Lading',
        icoon: '🕵️',
        beschrijving: 'Een handelaar op Mortex heeft een partij lunasteen die hij kwijt wil. De herkomst is vaag. Hij betaalt goed als jij ze aflevert op [bestemming] — geen reçu.',
        type: 'levering',
        vereistGoed: 'lunasteen',
        vereistHoeveelheid: 4,
        aantalPassagiers: null,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: true,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 5500,
        boeteCredits: 0,
        deadlineBeurten: 5,
        kans: 0.60,
        categorie: 'levering',
    },
    {
        id: 'mo_informant_evacueren',
        planeet: 'mortex',
        naam: 'Informant Evacueren',
        icoon: '🤫',
        beschrijving: 'Iemand weet te veel en moet van Mortex weg voordat bepaalde mensen dat weten. Twee personen, één bestemming, geen spoor achterlaten.',
        type: 'transport',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: 2,
        missieLadingType: null,
        missieLadingNaam: null,
        missieLadingIcoon: null,
        isVerdacht: true,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 13000,
        boeteCredits: 0,
        deadlineBeurten: 1,
        kans: 0.50,
        categorie: 'spoed',
    },
    {
        id: 'mo_gevoelige_lading',
        planeet: 'mortex',
        naam: 'Gevoelige Lading',
        icoon: '⚠️',
        beschrijving: 'Een zware krat met onbekende inhoud moet discreet naar [bestemming]. De opdrachtgever benadrukt: niet openen, niet vragen. Het betaalt navenant.',
        type: 'levering',
        vereistGoed: null,
        vereistHoeveelheid: null,
        aantalPassagiers: null,
        missieLadingType: 'pakket',
        missieLadingNaam: 'Zware krat (inhoud onbekend)',
        missieLadingIcoon: '⚠️',
        isVerdacht: true,
        ophaalPlaneet: null,
        bestemming: null,
        beloningCredits: 8500,
        boeteCredits: 0,
        deadlineBeurten: 4,
        kans: 0.45,
        categorie: 'levering',
    },
];

// =============================================================================
// TUTORIAL SYSTEEM — progressief feature-unlocken
// =============================================================================

const TUTORIAL_STAPPEN = [
    { beurt: 0,  feature: 'basis',           dialoog: { titel: 'Welkom, Kapitein!', tekst: 'Het jaar 3042. De melkweg bruist van handel en gevaar. Jij bent een beginnend ruimtehandelaar met één doel: zo rijk mogelijk worden in 150 beurten.\n\nKoop goederen goedkoop in op planeten waar ze geproduceerd worden, en verkoop ze met winst daar waar de vraag hoog is. Verken de 8 planeten, upgrade je schip en laat je fortuin groeien. Succes, Kapitein!' }},
    { beurt: 2,  feature: 'brandstof',       dialoog: { titel: 'Brandstof', tekst: 'Zonder brandstof kom je nergens. Je schip verbruikt brandstof per reisbeurt — hoe verder de bestemming, hoe meer je verbruikt. Tank op tijd bij. Op Pyroflux is brandstof het goedkoopst van de hele sector.' }},
    { beurt: 4,  feature: 'passagiers',      dialoog: { titel: 'Passagiers', tekst: 'Passagiers willen reizen! Op elke planeet wachten reizigers die een ticket willen kopen naar jouw volgende bestemming. Hoe meer passagierscapaciteit je schip heeft, hoe meer je kunt vervoeren. Passagiers betalen pas bij aankomst — dus kies je route slim.' }},
    { beurt: 6,  feature: 'leningen',        dialoog: { titel: 'Galactische Bank', tekst: 'De Galactische Bank is beschikbaar op elke planeet. Je kunt nu een lening afsluiten als je extra kapitaal nodig hebt. Leen verstandig — rente loopt op zolang je schuld uitstaat.' }},
    { beurt: 8,  feature: 'onderhoud',       dialoog: { titel: 'Onderhoud', tekst: 'Je schip loopt schade op bij gevaarlijke events. Bij lage HP vergroot de kans op mechanische defecten onderweg. Repareer je schip in de haven om problemen te voorkomen. Wacht niet te lang — een beschadigd schip is een risico.' }},
    { beurt: 10, feature: 'verzekering',     dialoog: { titel: 'Reisverzekering', tekst: 'Een verzekering dekt schade en ladingverlies bij ongelukken en gevaarlijke events. Zonder verzekering draag je alle risico\'s zelf. De premie is afhankelijk van je scheepstype en lading — beoordeel zelf of het de moeite waard is.' }},
    { beurt: 12, feature: 'bemanning',       dialoog: { titel: 'Bemanning', tekst: 'Je schip heeft een bemanning nodig om te functioneren. Je crew verwacht wekelijks salaris — mis je een betaling, dan daalt hun tevredenheid. Een ontevreden bemanning werkt langzamer en kan uiteindelijk in opstand komen. Houd ze tevreden.' }},
    { beurt: 14, feature: 'bank',            dialoog: { titel: 'Spaarrekening', tekst: 'Je kunt nu overtollige credits op een spaarrekening zetten om rente te verdienen.' }},
    { beurt: 16, feature: 'marketing',       dialoog: { titel: 'Marketing', tekst: 'Een marketingcampagne trekt extra passagiers aan op je volgende bestemming. Koop de campagne vóór vertrek — ze richt zich altijd op je geselecteerde reisdoel en vervalt zodra je landt. Slechts één campagne tegelijk mogelijk.' }},
    { beurt: 18, feature: 'beurs',           dialoog: { titel: 'Aandelenbeurs', tekst: 'De Galactische Beurs is exclusief beschikbaar op Nexoria. Hier kun je aandelen kopen en verkopen in zes galactische bedrijven. Koersen fluctueren elke beurt. Op andere planeten kun je je portfolio raadplegen, maar niet handelen.' }},
    { beurt: 20, feature: 'planeet_diensten',dialoog: { titel: 'Planeetdiensten', tekst: 'Elke planeet heeft unieke specialiteiten en diensten. Bezoek Techton voor scheepsupgrades, Luxoria voor het Casino Stellaris, Mortex voor de Zwarte Markt, en Pyroflux voor goedkope brandstof. Bij je eerste bezoek word je nader geïnformeerd.' }},
    { beurt: 24, feature: 'missies',         dialoog: { titel: 'Missies', tekst: 'Galactische opdrachtgevers staan klaar met lucratieve opdrachten en beloningen.' }},
];

// Koppeling event-ID → minimale feature-fase voor het op kunnen treden
// Events die niet in deze mapping staan vallen standaard onder 'planeet_diensten'
const EVENT_UNLOCK_FASE = {
    // Onderhoud (beurt 8)
    stralingstorm: 'onderhoud', nevel: 'onderhoud', asteroiden: 'onderhoud',
    defect: 'onderhoud', ruimtewrak: 'onderhoud', tip: 'onderhoud', cargo_lek: 'onderhoud',
    // Douane / verdachte lading (beurt 10)
    douane: 'verzekering', douaneboete: 'verzekering', smokkelbod: 'verzekering',
    // Bemanning (beurt 12)
    crew_opstand: 'bemanning', piraten: 'bemanning',
    // Bank / spaarrekening (beurt 14)
    bank_rente_omhoog: 'bank', bank_hoogconjunctuur: 'bank', bank_kredietexpansie: 'bank',
    bank_recessie: 'bank', bank_nulrente: 'bank', bank_crisis: 'bank',
    bank_belasting: 'bank', bank_bonus: 'bank', bank_bevriezing: 'bank',
    // Marketing (beurt 16)
    lifter: 'marketing', brandstof_vraag: 'marketing',
};

// Planeet-specifieke intro-dialogen (getoond bij eerste bezoek na unlock planeet_diensten)
const PLANEET_DIENSTEN_INTRO_DIALOGEN = {
    luxoria:  { titel: 'Casino Stellaris',  tekst: 'Het Casino Stellaris verwelkomt je. Trek een kaart en meet je kracht met de dealer — de hoogste kaart wint het dubbele terug. Bij gelijkspel krijg je je inzet terug. Maximaal 5 rondes per bezoek. Gok verstandig.' },
    mortex:   { titel: 'Zwarte Markt',      tekst: 'De Zwarte Markt van Mortex biedt alle goederen voor 35% onder de normale prijs. Verdachte lading trekt echter de aandacht van de douane — 25% kans op confiscatie bij elke aankomst elders. Koop een Afgeschermd Vrachtruim om dat risico te verlagen naar 5%.' },
    pyroflux: { titel: 'Energieboorpost',   tekst: 'De vulkanische energiereserves van Pyroflux maken dit de goedkoopste tankplek in de sector. Vul je tank hier zo vol mogelijk. Elke tankbeurt telt mee voor het Energieboer-achievement.' },
    techton:  { titel: 'Scheepswerf',       tekst: 'De geavanceerde scheepswerf op Techton kan je schip upgraden naar het volgende Mark. Je huidige schip wordt ingenomen voor 60% van de aankoopprijs. Upgraden gaat stap voor stap — je kunt geen Marks overslaan. Je scheepstype blijft permanent.' },
};

// Achievement-categorie → minimale feature-fase
const ACHIEVEMENT_CATEGORIE_FEATURE = {
    deals: 'basis', nettowaarde: 'basis', events: 'basis', schip: 'basis',
    beurs: 'beurs', financien: 'leningen',
};

// =============================================================================
// PLANEET AANKOMST EVENTS — spelen af bij landing op een planeet
// =============================================================================
const PLANEET_EVENTS = [
    {
        id: 'gewapend_conflict',
        naam: 'Gewapend Conflict',
        icoon: '⚔️',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een gewapend conflict heeft de aanvoerroutes verstoord. Technoware en Quantumchips zijn tijdelijk 80% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['technoware', 'quantumchips'], factor: 1.8 },
    },
    {
        id: 'handelsfestival',
        naam: 'Handelsfestival',
        icoon: '🎪',
        kans: 0.07,
        beschrijving: 'De jaarlijkse galactische handelsmarkt is in volle gang! Alle goederen zijn vandaag 15% goedkoper.',
        effect: { type: 'kortingAlles', factor: 0.85 },
    },
    {
        id: 'rijke_oogst',
        naam: 'Overrijke Oogst',
        icoon: '🌾',
        kans: 0.06,
        beschrijving: 'Een uitzonderlijk goede oogst heeft de voedselmarkt overspoeld. Nebulakorrels en Aquapure zijn spotgoedkoop.',
        effect: { type: 'prijsVerlaging', goederen: ['nebulakorrels', 'aquapure'], factor: 0.5 },
    },
    {
        id: 'energiecrisis',
        naam: 'Energiecrisis',
        icoon: '🔋',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een storing in de energiecentrale heeft de haven getroffen. Pyrogel en Kristalliet zijn vandaag extra duur.',
        effect: { type: 'prijsVerhoging', goederen: ['pyrogel', 'kristalliet'], factor: 2.0 },
    },
    {
        id: 'tech_doorbraak',
        naam: 'Technologische Doorbraak',
        icoon: '🔬',
        kans: 0.05,
        beschrijving: 'Lokale wetenschappers maakten een baanbrekende ontdekking. Technoware en Quantumchips zijn tijdelijk 35% goedkoper.',
        effect: { type: 'prijsVerlaging', goederen: ['technoware', 'quantumchips'], factor: 0.65 },
    },
    {
        id: 'piraten_aanval',
        naam: 'Pirateninval',
        icoon: '💀',
        type: 'gevaar',
        kans: 0.04,
        beschrijving: 'Piraten hebben de haven aangevallen tijdens jouw landing. Een deel van je lading is gestolen!',
        effect: { type: 'ladingStelen', fractie: 0.1 },
    },
    {
        id: 'markt_crash',
        naam: 'Lokale Marktcrash',
        icoon: '📉',
        kans: 0.04,
        beschrijving: 'Speculanten hebben de lokale markt doen crashen. Alle goederen zijn vandaag 20% goedkoper — maar kopers zijn ook schaars.',
        effect: { type: 'kortingAlles', factor: 0.8 },
    },
    {
        id: 'zwarte_markt',
        naam: 'Zwarte Markt Actief',
        icoon: '🕵️',
        kans: 0.05,
        beschrijving: 'Een ondergrondse markt biedt Luxuriet en Lunasteen aan voor slechts de helft van de normale prijs. Grijp je kans!',
        effect: { type: 'prijsVerlaging', goederen: ['luxuriet', 'lunasteen'], factor: 0.5 },
    },
    {
        id: 'handelsblokkade',
        naam: 'Galactische Handelsblokkade',
        icoon: '🚫',
        type: 'gevaar',
        kans: 0.03,
        beschrijving: 'Autoriteiten hebben een handelsblokkade uitgevaardigd. Luxe goederen en edelstenen zijn 60% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['luxuriet', 'lunasteen'], factor: 1.6 },
    },
    {
        id: 'voedselschaarste',
        naam: 'Voedselschaarste',
        icoon: '🆘',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een mislukte oogst heeft geleid tot ernstige voedseltekorten. Nebulakorrels en Aquapure zijn enorm in prijs gestegen!',
        effect: { type: 'prijsVerhoging', goederen: ['nebulakorrels', 'aquapure'], factor: 2.2 },
    },
    {
        id: 'mijnwerkerstaking',
        naam: 'Mijnwerkerstaking',
        icoon: '✊',
        kans: 0.05,
        beschrijving: 'Mijnwerkers staken voor betere arbeidsomstandigheden. Ferroiet en Kristalliet zijn tijdelijk niet te krijgen voor normale prijs.',
        effect: { type: 'prijsVerhoging', goederen: ['ferroiet', 'kristalliet'], factor: 1.9 },
    },
    { id: 'havenbelasting', naam: 'Havenheffing', icoon: '🚢', kans: 0.05, type: 'gevaar', beschrijving: 'De havenautoriteiten hebben een tijdelijke heffing ingevoerd op alle inkomende schepen. Je betaalt 350 credits bij aankomst.', effect: { type: 'kredietVerlies', bedrag: 350 } },
    { id: 'bevolkingsfeest', naam: 'Koloniedag', icoon: '🎆', kans: 0.06, beschrijving: 'De planeet viert haar stichtingsjubileum! De bevolking is in feeststemming. Alle prijzen zijn 20% hoger.', effect: { type: 'opwaarderingAlles', factor: 1.20 } },
    { id: 'medische_nood', naam: 'Medische Noodsituatie', icoon: '🏥', kans: 0.04, type: 'gevaar', beschrijving: 'De havenautoriteiten vorderen dringend Bioplasma wegens een epidemie. Ze betalen de basismarktwaarde.', effect: { type: 'ladingVordering', goed: 'bioplasma', ton: 10, prijs: 175 }, conditie: (state) => (state.lading?.bioplasma || 0) > 0 },
    { id: 'piraten_haven', naam: 'Piratentol bij de Haven', icoon: '☠️', kans: 0.04, type: 'gevaar', beschrijving: 'Piraten controleren de aanvliegroute en eisen tol van elk binnenkomend schip. 500 credits om door te mogen.', effect: { type: 'haventol', bedrag: 500 } },
];
