// =============================================================================
// GAZILLIONAIRE: STER DER HANDEL - Game Data
// =============================================================================

const PLANETEN = [
    {
        id: 'nexoria',
        naam: 'Nexoria',
        beschrijving: 'De grootste handelshub van de sector. Ideale startplek voor handelaars, met de aandelenbeurs en een volledig uitgeruste bank.',
        kleur: '#4a9eff',
        x: 50, y: 50,
        specialiteit: [],
        vraag: [],
    },
    {
        id: 'ferrum',
        naam: 'Ferrum',
        beschrijving: 'Een rotsachtige mijnbouwplaneet vol mineralen. De arbeiders leven hard en de vraag naar allerlei goederen fluctueert sterk.',
        kleur: '#c8753a',
        x: 18, y: 28,
        specialiteit: ['ferroiet', 'lunasteen'],
        vraag: ['nebulakorrels', 'aquapure'],
    },
    {
        id: 'agria',
        naam: 'Agria',
        beschrijving: 'Een weelderige landbouwplaneet met uitgestrekte velden. Prijzen fluctueren naar gelang de oogst en exportvraag.',
        kleur: '#39a85a',
        x: 80, y: 22,
        specialiteit: ['nebulakorrels', 'aquapure'],
        vraag: ['technoware', 'quantumchips'],
    },
    {
        id: 'techton',
        naam: 'Techton',
        beschrijving: 'Het technologiecentrum van de sector. Fabrieken en labs draaien dag en nacht, met constant wisselende vraag naar grondstoffen.',
        kleur: '#9b59ff',
        x: 82, y: 72,
        specialiteit: ['technoware', 'quantumchips'],
        vraag: ['pyrogel', 'ferroiet'],
    },
    {
        id: 'aqueron',
        naam: 'Aqueron',
        beschrijving: 'Een oceaanplaneet met uitgebreide biotechnologie. De handelspost is druk bezocht en prijzen reageren sterk op aanbod.',
        kleur: '#00aadd',
        x: 25, y: 75,
        specialiteit: ['bioplasma', 'aquapure'],
        vraag: ['luxuriet', 'lunasteen'],
    },
    {
        id: 'pyroflux',
        naam: 'Pyroflux',
        beschrijving: 'Een vulkanische planeet met enorme energiereserves. Extreme omstandigheden zorgen voor onvoorspelbare markten.',
        kleur: '#e03a3a',
        x: 12, y: 60,
        specialiteit: ['pyrogel', 'kristalliet'],
        vraag: ['nebulakorrels', 'bioplasma'],
    },
    {
        id: 'luxoria',
        naam: 'Luxoria',
        beschrijving: 'Het rijkste resortplaneet van de melkweg. Exclusieve clientèle zorgt voor hoge omzet en grillige prijsbewegingen.',
        kleur: '#d4ac0d',
        x: 65, y: 88,
        specialiteit: ['luxuriet', 'lunasteen'],
        vraag: ['ferroiet', 'pyrogel'],
    },
    {
        id: 'mortex',
        naam: 'Mortex Station',
        beschrijving: 'Een vervallen ruimtestation op de rand van het systeem. Hier gelden andere regels — hoge risico\'s en hoge beloningen. De zwarte markt bloeit.',
        kleur: '#8b0000',
        x: 48, y: 12,
        specialiteit: [],
        vraag: [],
        isGevaarlijk: true,
    },
];

const GOEDEREN = [
    { id: 'ferroiet',     naam: 'Ferroiet',     icoon: '🔩', basisPrijs: 50,  gewicht: 1, beschrijving: 'Basismetaal voor bouw en productie' },
    { id: 'kristalliet',  naam: 'Kristalliet',  icoon: '💠', basisPrijs: 115, gewicht: 1, beschrijving: 'Energiekristallen voor reactoren en shields' },
    { id: 'nebulakorrels',naam: 'Nebulakorrels',icoon: '🌾', basisPrijs: 32,  gewicht: 2, beschrijving: 'Voedzame graankorrels; basisvoedsel voor kolonies' },
    { id: 'bioplasma',    naam: 'Bioplasma',    icoon: '💉', basisPrijs: 175, gewicht: 1, beschrijving: 'Medische basistof voor behandelingen' },
    { id: 'technoware',   naam: 'Technoware',   icoon: '🔌', basisPrijs: 145, gewicht: 1, beschrijving: 'Elektronische componenten en modules' },
    { id: 'quantumchips', naam: 'Quantumchips', icoon: '💾', basisPrijs: 375, gewicht: 1, beschrijving: 'Geavanceerde kwantumprocessors' },
    { id: 'aquapure',     naam: 'Aquapure',     icoon: '💧', basisPrijs: 42,  gewicht: 3, beschrijving: 'Gezuiverd water voor menselijke kolonies' },
    { id: 'pyrogel',      naam: 'Pyrogel',      icoon: '⛽', basisPrijs: 82,  gewicht: 2, beschrijving: 'Hoogenergetische ruimtebrandstof' },
    { id: 'luxuriet',     naam: 'Luxuriet',     icoon: '👑', basisPrijs: 440, gewicht: 1, beschrijving: 'Allerhande luxe artikelen en statussymbolen' },
    { id: 'lunasteen',    naam: 'Lunasteen',    icoon: '💎', basisPrijs: 310, gewicht: 1, beschrijving: 'Zeldzame edelstenen van buitenste manen' },
];

const SCHEPEN = [
    // === VRACHTSCHIP ===
    {
        id: 'vracht_1',
        type: 'vracht',
        mark: 1,
        specialisatie: null,
        naam: 'Vrachtschip Mark I',
        icoon: '🚛',
        beschrijving: 'Robuust vrachtschip. Langzaam maar met ruim laadvermogen. De ruggengraat van de interplanetaire handel.',
        prijs: 16000,
        snelheid: 1,
        laadruimte: 60,
        schild: 2,
        kleur: '#8B6914',
        passagiersCapaciteit: 2,
        brandstofTank: 100,
        maxHP: 50,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_2',
        type: 'vracht',
        mark: 2,
        specialisatie: null,
        naam: 'Vrachtschip Mark II',
        icoon: '🚛',
        beschrijving: 'Verbeterd vrachtschip met grotere laadruimte en verstevigde romp. Bewezen workhorse.',
        prijs: 65000,
        snelheid: 1,
        laadruimte: 100,
        schild: 3,
        kleur: '#A07820',
        passagiersCapaciteit: 3,
        brandstofTank: 120,
        maxHP: 70,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_3a',
        type: 'vracht',
        mark: 3,
        specialisatie: 'a',
        naam: 'Tanker Mark III',
        icoon: '🛢️',
        beschrijving: 'Gespecialiseerd in het vervoer van vloeibare resources. Enorme laadruimte voor grondstoffen als Pyrogel, Aquapure en Bioplasma.',
        prijs: 210000,
        snelheid: 1,
        laadruimte: 220,
        schild: 3,
        kleur: '#6B8E23',
        passagiersCapaciteit: 2,
        brandstofTank: 150,
        maxHP: 90,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_3b',
        type: 'vracht',
        mark: 3,
        specialisatie: 'b',
        naam: 'Secure Hauler Mark III',
        icoon: '🔒',
        beschrijving: 'Gepantserd vrachtschip voor luxe en waardevolle lading. Immuun voor piraten. Mortex-lading wordt nooit geconfisqueerd.',
        prijs: 210000,
        snelheid: 2,
        laadruimte: 130,
        schild: 5,
        kleur: '#4169E1',
        passagiersCapaciteit: 2,
        brandstofTank: 150,
        maxHP: 90,
        immuunPiraten: true,
        immuunMortexConfiscatie: true,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_4a',
        type: 'vracht',
        mark: 4,
        specialisatie: 'a',
        naam: 'Tanker Mark IV',
        icoon: '🛢️',
        beschrijving: 'De ultieme tanker. Monsterlijke laadcapaciteit voor vloeibare grondstoffen. Verplaatst marktprijzen bij aankomst.',
        prijs: 680000,
        snelheid: 2,
        laadruimte: 350,
        schild: 4,
        kleur: '#7BAA2A',
        passagiersCapaciteit: 3,
        brandstofTank: 180,
        maxHP: 120,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'vracht_4b',
        type: 'vracht',
        mark: 4,
        specialisatie: 'b',
        naam: 'Secure Hauler Mark IV',
        icoon: '🔒',
        beschrijving: 'Onneembaar pantservrachtschip. Geen enkel gevaar kan je lading bereiken.',
        prijs: 680000,
        snelheid: 2,
        laadruimte: 170,
        schild: 5,
        kleur: '#4A79F1',
        passagiersCapaciteit: 3,
        brandstofTank: 180,
        maxHP: 120,
        immuunPiraten: true,
        immuunMortexConfiscatie: true,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    // === PASSAGIERSSCHIP ===
    {
        id: 'pax_1',
        type: 'pax',
        mark: 1,
        specialisatie: null,
        naam: 'Passagiersschip Mark I',
        icoon: '🛳️',
        beschrijving: 'Comfortabel passagiersschip. Trekt reizigers aan op alle routes met een goed serviceniveau.',
        prijs: 18000,
        snelheid: 2,
        laadruimte: 15,
        schild: 2,
        kleur: '#1E90FF',
        passagiersCapaciteit: 20,
        brandstofTank: 90,
        maxHP: 50,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'pax_2',
        type: 'pax',
        mark: 2,
        specialisatie: null,
        naam: 'Passagiersschip Mark II',
        icoon: '🛳️',
        beschrijving: 'Verbeterd passagiersschip met dubbele capaciteit en comfortabelere inrichting.',
        prijs: 70000,
        snelheid: 2,
        laadruimte: 20,
        schild: 2,
        kleur: '#2EA0FF',
        passagiersCapaciteit: 40,
        brandstofTank: 110,
        maxHP: 65,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'pax_3a',
        type: 'pax',
        mark: 3,
        specialisatie: 'a',
        naam: 'Luxury Liner Mark III',
        icoon: '🥂',
        beschrijving: 'Exclusief luxejacht voor de galactische elite. Minder passagiers, maar zij betalen driemaal de normale ticketprijs.',
        prijs: 220000,
        snelheid: 3,
        laadruimte: 20,
        schild: 3,
        kleur: '#FFD700',
        passagiersCapaciteit: 20,
        brandstofTank: 130,
        maxHP: 85,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 3,
        spearheadBonus: false,
    },
    {
        id: 'pax_3b',
        type: 'pax',
        mark: 3,
        specialisatie: 'b',
        naam: 'Space Bus Mark III',
        icoon: '🚌',
        beschrijving: 'Maximale capaciteit voor massa-transport. Lage ticketprijs trekt grote aantallen passagiers aan.',
        prijs: 220000,
        snelheid: 2,
        laadruimte: 20,
        schild: 2,
        kleur: '#FF8C00',
        passagiersCapaciteit: 80,
        brandstofTank: 130,
        maxHP: 85,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 0.5,
        spearheadBonus: false,
    },
    {
        id: 'pax_4a',
        type: 'pax',
        mark: 4,
        specialisatie: 'a',
        naam: 'Luxury Liner Mark IV',
        icoon: '🥂',
        beschrijving: 'Het summum van galactische luxe. Alleen de rijksten kunnen zich een ticket veroorloven.',
        prijs: 700000,
        snelheid: 3,
        laadruimte: 25,
        schild: 4,
        kleur: '#FFE030',
        passagiersCapaciteit: 24,
        brandstofTank: 150,
        maxHP: 110,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 3,
        spearheadBonus: false,
    },
    {
        id: 'pax_4b',
        type: 'pax',
        mark: 4,
        specialisatie: 'b',
        naam: 'Space Bus Mark IV',
        icoon: '🚌',
        beschrijving: 'De galactische volksvervoerder. Transporteert een halve kolonie per rit.',
        prijs: 700000,
        snelheid: 2,
        laadruimte: 25,
        schild: 2,
        kleur: '#FFA020',
        passagiersCapaciteit: 120,
        brandstofTank: 150,
        maxHP: 110,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 0.5,
        spearheadBonus: false,
    },
    // === SNEL SCHIP ===
    {
        id: 'snel_1',
        type: 'snel',
        mark: 1,
        specialisatie: null,
        naam: 'Snel Schip Mark I',
        icoon: '✈️',
        beschrijving: 'Licht en snel. Kleine laadruimte, maar arriveert eerder dan de concurrentie. Ideaal voor opportunistische handel.',
        prijs: 19000,
        snelheid: 3,
        laadruimte: 20,
        schild: 1,
        kleur: '#FF6B35',
        passagiersCapaciteit: 4,
        brandstofTank: 70,
        maxHP: 45,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_2',
        type: 'snel',
        mark: 2,
        specialisatie: null,
        naam: 'Snel Schip Mark II',
        icoon: '✈️',
        beschrijving: 'Opgewaardeerde snelle courier. Meer laadruimte zonder snelheid in te leveren.',
        prijs: 75000,
        snelheid: 5,
        laadruimte: 30,
        schild: 1,
        kleur: '#FF7B45',
        passagiersCapaciteit: 6,
        brandstofTank: 85,
        maxHP: 60,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_3a',
        type: 'snel',
        mark: 3,
        specialisatie: 'a',
        naam: 'Spearhead Mark III',
        icoon: '⚡',
        beschrijving: 'Snelste schip in de sector. Arriveert altijd vóór de concurrenten en pakt een marktkorting van 8% mee op alle aankoopprijzen.',
        prijs: 235000,
        snelheid: 8,
        laadruimte: 40,
        schild: 2,
        kleur: '#FFD700',
        passagiersCapaciteit: 6,
        brandstofTank: 100,
        maxHP: 75,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: true,
    },
    {
        id: 'snel_3b',
        type: 'snel',
        mark: 3,
        specialisatie: 'b',
        naam: 'Shadow Mark III',
        icoon: '🌑',
        beschrijving: 'Onzichtbaar smokkelschip. Piraten negeren je volledig. Douanekans drastisch verlaagd naar 5%. Perfect voor Mortex-routes.',
        prijs: 235000,
        snelheid: 7,
        laadruimte: 45,
        schild: 1,
        kleur: '#6A0DAD',
        passagiersCapaciteit: 4,
        brandstofTank: 95,
        maxHP: 75,
        immuunPiraten: true,
        immuunMortexConfiscatie: false,
        douaneKansOverride: 0.05,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
    {
        id: 'snel_4a',
        type: 'snel',
        mark: 4,
        specialisatie: 'a',
        naam: 'Spearhead Mark IV',
        icoon: '⚡',
        beschrijving: 'Ongeëvenaarde snelheid. Geen enkele concurrent arriveert eerder. Maximale marktkorting van 8% gegarandeerd.',
        prijs: 740000,
        snelheid: 10,
        laadruimte: 50,
        schild: 3,
        kleur: '#FFDF20',
        passagiersCapaciteit: 8,
        brandstofTank: 115,
        maxHP: 100,
        immuunPiraten: false,
        immuunMortexConfiscatie: false,
        douaneKansOverride: null,
        ticketMultiplier: 1,
        spearheadBonus: true,
    },
    {
        id: 'snel_4b',
        type: 'snel',
        mark: 4,
        specialisatie: 'b',
        naam: 'Shadow Mark IV',
        icoon: '🌑',
        beschrijving: 'Het ultieme spookschip. Radaronzichtbaar, piratenimmuun, douaneonzichtbaar. Beheers de zwarte markt.',
        prijs: 740000,
        snelheid: 9,
        laadruimte: 60,
        schild: 1,
        kleur: '#7A1DBD',
        passagiersCapaciteit: 4,
        brandstofTank: 110,
        maxHP: 100,
        immuunPiraten: true,
        immuunMortexConfiscatie: false,
        douaneKansOverride: 0.05,
        ticketMultiplier: 1,
        spearheadBonus: false,
    },
];

const UPGRADES = [];

// Crew-grootte per schip (bemanning vereist voor bediening)
const CREW_PER_SCHIP = {
    vracht_1: 3,  vracht_2: 5,  vracht_3a: 8,  vracht_3b: 7,  vracht_4a: 12, vracht_4b: 10,
    pax_1:    4,  pax_2:    6,  pax_3a:   10,  pax_3b:    7,  pax_4a:   14,  pax_4b:   10,
    snel_1:   2,  snel_2:   3,  snel_3a:   5,  snel_3b:    4,  snel_4a:   7,  snel_4b:    6,
};

// Kansen optellen naar 1.0
const EVENTS = [
    {
        id: 'piraten',
        naam: 'Ruimtepiraten!',
        icoon: '☠️',
        type: 'gevaar',
        kans: 0.10,
        beschrijving: 'Een piratengroep onderschept je schip en blokkeert je route. Ze eisen tol voor veilige doorgang.',
        heeftKeuze: true,
        keuzes: [
            { id: 'betaal', tekst: 'Betaal het losgeld', stijl: 'gevaar' },
            { id: 'vlucht', tekst: 'Probeer te ontsnappen', stijl: 'knop' },
        ],
    },
    {
        id: 'stralingstorm',
        naam: 'Stralingstorm',
        icoon: '⚡',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een zware stralingstorm treft je route. Je moet een grote omweg nemen — dat kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'ruimtewrak',
        naam: 'Ruimtewrak Gevonden',
        icoon: '🛸',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Je detecteert een verlaten handelsschip. Na onderzoek vind je nog bruikbare lading aan boord!',
        heeftKeuze: false,
    },
    {
        id: 'defect',
        naam: 'Mechanisch Defect',
        icoon: '🔧',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Een cruciaal onderdeel geeft het op. Je moet halverwege stoppen voor noodreparaties.',
        heeftKeuze: true,
        keuzes: [
            { id: 'repareer', tekst: 'Repareer direct (400 credits)', stijl: 'gevaar' },
            { id: 'doorvaren', tekst: 'Doorvaren met beschadiging', stijl: 'knop' },
        ],
    },
    {
        id: 'smokkelbod',
        naam: 'Sluiksmokkelaar',
        icoon: '🤫',
        type: 'kans',
        kans: 0.07,
        beschrijving: 'Een mysterieuze smokkelaar biedt je goederen aan ver onder de marktprijs. Riskant, maar potentieel winstgevend.',
        heeftKeuze: true,
        keuzes: [
            { id: 'koop', tekst: 'Koop de goederen', stijl: 'succes' },
            { id: 'weiger', tekst: 'Weiger het aanbod', stijl: 'knop' },
        ],
    },
    {
        id: 'nevel',
        naam: 'Ionennevel',
        icoon: '🌫️',
        type: 'neutraal',
        kans: 0.08,
        beschrijving: 'Je vliegt door een dichte ionennevel. Navigatiesystemen raken verstoord — de omweg kost extra brandstof.',
        heeftKeuze: false,
    },
    {
        id: 'tip',
        naam: 'Handelstip',
        icoon: '💡',
        type: 'kans',
        kans: 0.09,
        beschrijving: 'Je ontmoet een vriendelijke ruimtekapitein die je een waardevolle tip geeft over de marktprijzen!',
        heeftKeuze: false,
    },
    {
        id: 'asteroiden',
        naam: 'Asteroïdenveld',
        icoon: '🪨',
        type: 'gevaar',
        kans: 0.09,
        beschrijving: 'Je vliegt onverwacht een dicht asteroïdenveld in. Je schip loopt averij op!',
        heeftKeuze: false,
    },
    {
        id: 'douane',
        naam: 'Douanecontrole',
        icoon: '🔍',
        type: 'neutraal',
        kans: 0.07,
        beschrijving: 'Galactische douaniers stoppen je voor een grondige controle. Ze kijken of alles in orde is.',
        heeftKeuze: false,
    },
    {
        id: 'bonus',
        naam: 'Galactische Subsidie',
        icoon: '🎁',
        type: 'kans',
        kans: 0.06,
        beschrijving: 'Gefeliciteerd! Je ontvangt een onverwachte handelssubsidie van de Galactische Handelsgilde!',
        heeftKeuze: false,
    },
    {
        id: 'brandstof_vraag',
        naam: 'Noodoproep: Brandstof',
        icoon: '🆘',
        type: 'neutraal',
        kans: 0.05,
        beschrijving: 'Een gestrande ruimtepiloot roept je via de noodfrequentie op. Ze zit zonder brandstof en vraagt om hulp.',
        heeftKeuze: true,
        keuzes: [
            { id: 'geef', tekst: 'Geef 20 liter brandstof', stijl: 'succes' },
            { id: 'weiger', tekst: 'Vlieg door', stijl: 'knop' },
        ],
    },
    {
        id: 'lifter',
        naam: 'Ruimtelift Gevraagd',
        icoon: '🧳',
        type: 'kans',
        kans: 0.08,
        beschrijving: 'Een reiziger wil meelliften naar je bestemming.', // dynamic in UI
        heeftKeuze: true,
        keuzes: [
            { id: 'meenemen', tekst: 'Neem de lifter mee', stijl: 'succes' },
            { id: 'weiger', tekst: 'Rijd door', stijl: 'knop' },
        ],
    },
    {
        id: 'bederf',
        naam: 'Goederen Bedorven!',
        icoon: '🤢',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Door een storing in je koelsysteem zijn een deel van je goederen bedorven. Je verliest de helft!',
        heeftKeuze: false,
    },
    {
        id: 'haven_gesloten',
        naam: 'Ruimtehaven Gesloten',
        icoon: '🚫',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'De ruimtehaven van je bestemming is plotseling gesloten vanwege een quarantaineprotocol. Je moet noodkoers zetten naar de dichtstbijzijnde alternatieve haven.',
        heeftKeuze: false,
    },
    {
        id: 'noodlanding',
        naam: 'Noodlanding',
        icoon: '🆘',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een kritische motorsysteem storing dwingt je tot een noodlanding op de dichtstbijzijnde planeet. Je geplande bestemming is niet meer haalbaar.',
        heeftKeuze: false,
    },
    {
        id: 'douaneboete',
        naam: 'Galactische Douaneboete',
        icoon: '🚨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Douaneinspecteurs leggen een fikse boete op wegens een papierwerk-overtreding. Je moet direct betalen.',
        heeftKeuze: false,
    },
    {
        id: 'cargo_lek',
        naam: 'Containerlek',
        icoon: '💨',
        type: 'gevaar',
        kans: 0.07,
        beschrijving: 'Een container heeft een druklek. Kostbare lading is in de ruimte verdwenen voor je het door had.',
        heeftKeuze: false,
    },
    {
        id: 'motordiefstal',
        naam: 'Ruimtediefstal',
        icoon: '🦹',
        type: 'gevaar',
        kans: 0.06,
        beschrijving: 'Een listige ruimtecrimineel heeft onopgemerkt je vrachtruim doorzocht en credits buitgemaakt.',
        heeftKeuze: false,
    },
    {
        id: 'niets',
        naam: 'Rustige reis',
        icoon: '🌟',
        type: 'neutraal',
        kans: 0.18,
        beschrijving: 'De reis verloopt vlekkeloos. Sterrenbeelden passeren, je koers is recht, en alles is in orde.',
        heeftKeuze: false,
    },
    {
        id: 'crew_opstand',
        naam: 'Crew Opstand!',
        icoon: '✊',
        type: 'gevaar',
        kans: 0,   // Alleen getriggerd door geluk-check; nooit via normale pool
        beschrijving: 'Je bemanning is tot het uiterste gedreven. Ze eisen onmiddellijke betaling, anders leggen ze het werk neer.',
        heeftKeuze: true,
        keuzes: [
            { id: 'betaal', tekst: 'Betaal dubbel salaris', stijl: 'gevaar' },
            { id: 'praten', tekst: 'Onderhandel (50% kans)', stijl: 'knop' },
        ],
    },
    // === BANK EVENTS ===
    {
        id: 'bank_rente_omhoog',
        naam: 'Galactische Monetaire Unie verhoogt basisrente',
        icoon: '🏦',
        type: 'positief',
        kans: 0.04,
        beschrijving: 'De Galactische Monetaire Unie heeft de basisrente verhoogd. Je spaarrente stijgt met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_hoogconjunctuur',
        naam: 'Economische Hoogconjunctuur',
        icoon: '📈',
        type: 'positief',
        kans: 0.03,
        beschrijving: 'Een periode van economische bloei. Alle banken verhogen hun rente tijdelijk met 1%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_kredietexpansie',
        naam: 'Kredietexpansie in de Buitenste Ring',
        icoon: '💹',
        type: 'positief',
        kans: 0.04,
        beschrijving: 'Een nieuwe kredietlijn wordt opengesteld door de Galactische Handelsbank. Spaarrente stijgt met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_recessie',
        naam: 'Intergalactische Recessie Dreigt',
        icoon: '📉',
        type: 'gevaar',
        kans: 0.04,
        beschrijving: 'Economische onzekerheid trekt door de melkweg. Bankrentes dalen met 0.5%.',
        heeftKeuze: false,
    },
    {
        id: 'bank_nulrente',
        naam: 'Centrale Bank Voert Nulrentebeleid In',
        icoon: '🏛️',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'De Galactische Centrale Bank verlaagt de rente naar nul. Je spaargeld groeit tijdelijk niet meer.',
        heeftKeuze: false,
    },
    {
        id: 'bank_crisis',
        naam: 'Bankcrisis op Nexoria',
        icoon: '⚠️',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'Een bankcrisis heeft de sector geschokt. Spaarrentes worden met 1% verlaagd.',
        heeftKeuze: false,
    },
    {
        id: 'bank_belasting',
        naam: 'Vermogensbelasting Galacticus',
        icoon: '💸',
        type: 'gevaar',
        kans: 0.03,
        beschrijving: 'De Belastingdienst Galacticus vordert 3% van je banksaldo als vermogensbelasting.',
        heeftKeuze: false,
    },
    {
        id: 'bank_bonus',
        naam: 'Spaarbonus-actie',
        icoon: '🎁',
        type: 'positief',
        kans: 0.03,
        beschrijving: 'Als trouwe rekeninghouder ontvang je een eenmalige spaarbonus van 500 credits.',
        heeftKeuze: false,
    },
    {
        id: 'bank_bevriezing',
        naam: 'Bankbevriezing door Politieke Onrust',
        icoon: '🔒',
        type: 'gevaar',
        kans: 0.02,
        beschrijving: 'Politieke onrust heeft alle banktransacties tijdelijk geblokkeerd. Storten en opnemen is de komende beurt niet mogelijk.',
        heeftKeuze: false,
    },
];

const AANDELEN = [
    { id: 'nexcorp',    naam: 'NexCorp Mining',    icoon: '⛏️', basisPrijs: 100, beschrijving: 'Mijnbouwconglomeraat actief op Ferrum' },
    { id: 'aquatech',   naam: 'AquaTech',           icoon: '💧', basisPrijs: 75,  beschrijving: 'Waterbehandeling en distributie' },
    { id: 'pyroenergie',naam: 'PyroEnergie NV',     icoon: '⚡', basisPrijs: 110, beschrijving: 'Brandstofproducent op Pyroflux' },
    { id: 'luxtrading', naam: 'LuxTrading Corp',    icoon: '💰', basisPrijs: 180, beschrijving: 'Premium luxehandel gericht op Luxoria' },
    { id: 'techstar',   naam: 'TechStar Industries',icoon: '🌟', basisPrijs: 140, beschrijving: 'Technologiepionier en innovator' },
    { id: 'biomed',     naam: 'BioMed Galax',       icoon: '💊', basisPrijs: 85,  beschrijving: 'Farmaceutisch concern met basis op Aqueron' },
];

const CONCURRENTEN = [
    {
        id: 'zax',
        naam: 'Handelaar Zax',
        icoon: '🦊',
        persoonlijkheid: 'Opportunist',
        beschrijving: 'Een nietsontziende opkoper die elke kans aangrijpt. Snel, gretig, en overal tegelijk aanwezig.',
        snelheid: 3,
        kleur: '#ff6b35',
        startKrediet: 4500,
        baseWinstPerBeurt: 900,
        volatiliteit: 0.13,
    },
    {
        id: 'mira',
        naam: 'Koopman Mira',
        icoon: '💼',
        persoonlijkheid: 'Strateeg',
        beschrijving: 'Berekend en gedisciplineerd. Mira plant elke zet en maakt zelden een fout — de gevaarlijkste concurrent.',
        snelheid: 2,
        kleur: '#00d4ff',
        startKrediet: 5500,
        baseWinstPerBeurt: 1100,
        volatiliteit: 0.05,
    },
    {
        id: 'rok',
        naam: 'Kapitein Rok',
        icoon: '⚡',
        persoonlijkheid: 'Avonturier',
        beschrijving: 'Onstuimig en razendsnel. Rok pikt de beste deals weg voor jij ze ziet, maar maakt ook spectaculaire missers.',
        snelheid: 4,
        kleur: '#ffd700',
        startKrediet: 3000,
        baseWinstPerBeurt: 850,
        volatiliteit: 0.10,
    },
    {
        id: 'voss',
        naam: 'Makelaar Voss',
        icoon: '🎩',
        persoonlijkheid: 'Veteraan',
        beschrijving: 'De oude reus van de handelswereld. Traag, maar zijn netwerk en ervaring leveren hem altijd een voordeel op.',
        snelheid: 1,
        kleur: '#9b59ff',
        startKrediet: 7000,
        baseWinstPerBeurt: 800,
        volatiliteit: 0.04,
    },
    {
        id: 'nyx',
        naam: 'Schaduw Nyx',
        icoon: '🕶️',
        persoonlijkheid: 'Mysterie',
        beschrijving: 'Niemand weet precies wat Nyx doet. Zijn vermogen fluctueert wild — soms verdwijnt het plots, soms verveelvoudigt het.',
        snelheid: 3,
        kleur: '#ff3855',
        startKrediet: 5000,
        baseWinstPerBeurt: 600,
        volatiliteit: 0.22,
    },
];

const ACHIEVEMENTS = [
    {
        id: 'eerste_deal',
        naam: 'Eerste Deal',
        icoon: '🤝',
        categorie: 'deals',
        beschrijving: 'Verkoop voor de eerste keer goederen.',
        beloning: 250,
        check: s => (s.statistieken.verkopen ?? 0) >= 1,
    },
    {
        id: 'tiental',
        naam: 'Actieve Handelaar',
        icoon: '📊',
        categorie: 'deals',
        beschrijving: 'Voltooi 10 handelstransacties.',
        beloning: 750,
        check: s => s.statistieken.handelstransacties >= 10,
    },
    {
        id: 'vijftig',
        naam: 'Handelsmagnaat',
        icoon: '🏪',
        categorie: 'deals',
        beschrijving: 'Voltooi 50 handelstransacties.',
        beloning: 3000,
        check: s => s.statistieken.handelstransacties >= 50,
    },
    {
        id: 'rijkaard',
        naam: 'Rijkaard',
        icoon: '💰',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 10.000 credits.',
        beloning: 1500,
        check: s => s.berekenNettowaarde() >= 10000,
    },
    {
        id: 'groot_handelaar',
        naam: 'Groot Handelaar',
        icoon: '🏛️',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 100.000 credits.',
        beloning: 7500,
        check: s => s.berekenNettowaarde() >= 100000,
    },
    {
        id: 'millionair',
        naam: 'Galactische Millionair',
        icoon: '🌟',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 1.000.000 credits.',
        beloning: 50000,
        check: s => s.berekenNettowaarde() >= 1000000,
    },
    {
        id: 'wereldreiziger',
        naam: 'Wereldreiziger',
        icoon: '🗺️',
        categorie: 'events',
        beschrijving: 'Bezoek alle 8 planeten.',
        beloning: 5000,
        check: s => s.bezochteplaneten && s.bezochteplaneten.size >= 8,
    },
    // Gazillionair
    {
        id: 'gazillionair',
        naam: 'Gazillionair',
        icoon: '🤑',
        categorie: 'nettowaarde',
        beschrijving: 'Bereik een nettowaarde van 25 miljoen credits.',
        beloning: 100000,
        check: s => s.berekenNettowaarde() >= 25000000,
    },
    // Schip — Vrachtschip
    {
        id: 'vracht_mark2',
        naam: 'Zware Vrachter',
        icoon: '🚛',
        categorie: 'schip',
        beschrijving: 'Vrachtschip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['vracht_2','vracht_3a','vracht_3b','vracht_4a','vracht_4b'].includes(s.schip?.id),
    },
    {
        id: 'tanker_mark3',
        naam: 'Vloeibare Goudader',
        icoon: '🛢️',
        categorie: 'schip',
        beschrijving: 'Tanker Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['vracht_3a','vracht_4a'].includes(s.schip?.id),
    },
    {
        id: 'secure_mark3',
        naam: 'Onaantastbaar',
        icoon: '🔒',
        categorie: 'schip',
        beschrijving: 'Secure Hauler Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['vracht_3b','vracht_4b'].includes(s.schip?.id),
    },
    {
        id: 'tanker_mark4',
        naam: 'Galactisch Tankschip',
        icoon: '🌊',
        categorie: 'schip',
        beschrijving: 'Tanker Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'vracht_4a',
    },
    {
        id: 'secure_mark4',
        naam: 'Fort Knox',
        icoon: '🏰',
        categorie: 'schip',
        beschrijving: 'Secure Hauler Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'vracht_4b',
    },
    // Schip — Passagiersschip
    {
        id: 'pax_mark2',
        naam: 'Ruimtevervoer',
        icoon: '🛳️',
        categorie: 'schip',
        beschrijving: 'Passagiersschip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['pax_2','pax_3a','pax_3b','pax_4a','pax_4b'].includes(s.schip?.id),
    },
    {
        id: 'luxury_mark3',
        naam: 'Ruimte-elite',
        icoon: '🥂',
        categorie: 'schip',
        beschrijving: 'Luxury Liner Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['pax_3a','pax_4a'].includes(s.schip?.id),
    },
    {
        id: 'spacebus_mark3',
        naam: 'Ruimtetaxi',
        icoon: '🚌',
        categorie: 'schip',
        beschrijving: 'Space Bus Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['pax_3b','pax_4b'].includes(s.schip?.id),
    },
    {
        id: 'luxury_mark4',
        naam: 'Galactische Luxe',
        icoon: '✨',
        categorie: 'schip',
        beschrijving: 'Luxury Liner Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'pax_4a',
    },
    {
        id: 'spacebus_mark4',
        naam: 'Galactische Bus',
        icoon: '🌌',
        categorie: 'schip',
        beschrijving: 'Space Bus Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'pax_4b',
    },
    // Schip — Snel Schip
    {
        id: 'snel_mark2',
        naam: 'Ruimteraket',
        icoon: '🚀',
        categorie: 'schip',
        beschrijving: 'Snel Schip opgewaardeerd naar Mark II.',
        beloning: 2000,
        check: s => ['snel_2','snel_3a','snel_3b','snel_4a','snel_4b'].includes(s.schip?.id),
    },
    {
        id: 'spearhead_mark3',
        naam: 'Altijd Als Eerste',
        icoon: '⚡',
        categorie: 'schip',
        beschrijving: 'Spearhead Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['snel_3a','snel_4a'].includes(s.schip?.id),
    },
    {
        id: 'shadow_mark3',
        naam: 'Schaduwhandelaar',
        icoon: '🌑',
        categorie: 'schip',
        beschrijving: 'Shadow Mark III aangeschaft.',
        beloning: 8000,
        check: s => ['snel_3b','snel_4b'].includes(s.schip?.id),
    },
    {
        id: 'spearhead_mark4',
        naam: 'Snelste van de Sector',
        icoon: '⚡',
        categorie: 'schip',
        beschrijving: 'Spearhead Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'snel_4a',
    },
    {
        id: 'shadow_mark4',
        naam: 'Ongrijpbaar',
        icoon: '🌑',
        categorie: 'schip',
        beschrijving: 'Shadow Mark IV aangeschaft.',
        beloning: 40000,
        check: s => s.schip?.id === 'snel_4b',
    },
    // Beurs
    {
        id: 'beurs_goeroe',
        naam: 'Beursgoeroe',
        icoon: '📈',
        categorie: 'beurs',
        beschrijving: 'Bezit 4 of meer verschillende aandelen tegelijk.',
        beloning: 2500,
        check: s => Object.values(s.aandelenPortefeuille).filter(v => v > 0).length >= 4,
    },
    {
        id: 'beurs_winst_1k',
        naam: 'Beurswinst',
        icoon: '💹',
        categorie: 'beurs',
        beschrijving: 'Maak 1.000 credits winst op één aandelenverkoop.',
        beloning: 1000,
        check: s => (s._beursBesteDeal ?? 0) >= 1000,
    },
    {
        id: 'beurs_winst_10k',
        naam: 'Beursmagnaat',
        icoon: '🏦',
        categorie: 'beurs',
        beschrijving: 'Maak 10.000 credits winst op één aandelenverkoop.',
        beloning: 5000,
        check: s => (s._beursBesteDeal ?? 0) >= 10000,
    },
    {
        id: 'beurs_totaal_25k',
        naam: 'Beursspeculant',
        icoon: '📊',
        categorie: 'beurs',
        beschrijving: 'Verdien 25.000 credits totaal via aandelenverkoop.',
        beloning: 3000,
        check: s => (s._beursWinstTotaal ?? 0) >= 25000,
    },
    {
        id: 'beurs_totaal_250k',
        naam: 'Galactisch Belegger',
        icoon: '🌟',
        categorie: 'beurs',
        beschrijving: 'Verdien 250.000 credits totaal via aandelenverkoop.',
        beloning: 20000,
        check: s => (s._beursWinstTotaal ?? 0) >= 250000,
    },
    // Handel
    {
        id: 'winstmaker',
        naam: 'Winstmaker',
        icoon: '💎',
        categorie: 'deals',
        beschrijving: 'Maak 1.000 credits winst op één deal.',
        beloning: 1500,
        check: s => s._laatsteWinst >= 1000,
    },
    {
        id: 'superdeal',
        naam: 'Superdeal',
        icoon: '🏆',
        categorie: 'deals',
        beschrijving: 'Maak 5.000 credits winst op één deal.',
        beloning: 5000,
        check: s => s._laatsteWinst >= 5000,
    },
    {
        id: 'reiziger',
        naam: 'Ruimtereiziger',
        icoon: '🚀',
        categorie: 'events',
        beschrijving: 'Maak 10 ruimtereizen.',
        beloning: 1500,
        check: s => s.statistieken.gereisd >= 10,
    },
    {
        id: 'schuldenvrij',
        naam: 'Schuldenvrij',
        icoon: '✅',
        categorie: 'nettowaarde',
        beschrijving: 'Betaal een lening volledig af.',
        beloning: 2000,
        check: s => s._oitLeningGehad && s.speler.schuld === 0,
    },
    {
        id: 'overlever',
        naam: 'Piratenontkomer',
        icoon: '⚡',
        categorie: 'events',
        beschrijving: 'Ontsnapt aan piraten.',
        beloning: 1000,
        check: s => s._piratenOntkomingen > 0,
    },
    {
        id: 'bijna_leeg',
        naam: 'Op de Rand',
        icoon: '⛽',
        categorie: 'events',
        beschrijving: 'Kom aan op een planeet met minder dan 10 liter brandstof.',
        beloning: 300,
        check: s => s._aangekomendMetLageBrandstof,
    },
    {
        id: 'eerste_passagier',
        naam: 'Taxiservice',
        icoon: '🧳',
        categorie: 'events',
        beschrijving: 'Lever je eerste passagier af op zijn bestemming.',
        beloning: 600,
        check: s => s.statistieken.passagiersAfgeleverd >= 1,
    },
    {
        id: 'veilingmeester',
        naam: 'Veilingmeester',
        icoon: '🔨',
        categorie: 'events',
        beschrijving: 'Win een oogstveiling op Agria.',
        beloning: 1000,
        check: s => (s.statistieken.veilingenGewonnen ?? 0) >= 1,
    },
    {
        id: 'alchemist',
        naam: 'Alchemist',
        icoon: '🧪',
        categorie: 'schip',
        beschrijving: 'Verwerk in totaal 30 ton Ferroiet in de ertsverwerkingsfaciliteit op Ferrum.',
        beloning: 1500,
        check: s => (s.statistieken.ferroietVerwerkt ?? 0) >= 30,
    },
    {
        id: 'energieboer',
        naam: 'Energieboer',
        icoon: '⚡',
        categorie: 'reizen',
        beschrijving: 'Tank 10× op het Energiedepot van Pyroflux.',
        beloning: 600,
        check: s => (s.statistieken.pyrofluxTankbeurten ?? 0) >= 10,
    },
    {
        id: 'huisvoordeel',
        naam: 'Huisvoordeel',
        icoon: '🃏',
        categorie: 'events',
        beschrijving: 'Win 3× op rij in het Casino Stellaris op Luxoria.',
        beloning: 1200,
        check: s => (s.statistieken.casinoWinstStreak ?? 0) >= 3,
    },
    {
        id: 'jackpot',
        naam: 'Jackpot',
        icoon: '🎰',
        categorie: 'events',
        beschrijving: 'Win 3.000+ credits in één gokbeurt.',
        beloning: 2500,
        check: s => (s.statistieken.casinoBigWin ?? 0) >= 1,
    },
    {
        id: 'zwarthandelaar',
        naam: 'Zwarthandelaar',
        icoon: '🕵️',
        categorie: 'handel',
        beschrijving: 'Vervoer verdachte lading van Mortex zonder gepakt te worden.',
        beloning: 1000,
        check: s => (s.statistieken.mortexGladGestreken ?? 0) >= 1,
    },
    {
        id: 'bank_100k',
        naam: 'Stevige Spaarpot',
        icoon: '🏦',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 100.000 credits.',
        beloning: 5000,
        check: s => (s.bankSaldo ?? 0) >= 100000,
    },
    {
        id: 'bank_250k',
        naam: 'Galactisch Vermogen',
        icoon: '💰',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 250.000 credits.',
        beloning: 10000,
        check: s => (s.bankSaldo ?? 0) >= 250000,
    },
    {
        id: 'bank_500k',
        naam: 'Ruimtebankier',
        icoon: '💎',
        categorie: 'financien',
        beschrijving: 'Bereik een banksaldo van 500.000 credits.',
        beloning: 25000,
        check: s => (s.bankSaldo ?? 0) >= 500000,
    },
];

// =============================================================================
// PLANEET AANKOMST EVENTS — spelen af bij landing op een planeet
// =============================================================================
const PLANEET_EVENTS = [
    {
        id: 'gewapend_conflict',
        naam: 'Gewapend Conflict',
        icoon: '⚔️',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een gewapend conflict heeft de aanvoerroutes verstoord. Technoware en Quantumchips zijn tijdelijk 80% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['technoware', 'quantumchips'], factor: 1.8 },
    },
    {
        id: 'handelsfestival',
        naam: 'Handelsfestival',
        icoon: '🎪',
        kans: 0.07,
        beschrijving: 'De jaarlijkse galactische handelsmarkt is in volle gang! Alle goederen zijn vandaag 15% goedkoper.',
        effect: { type: 'kortingAlles', factor: 0.85 },
    },
    {
        id: 'rijke_oogst',
        naam: 'Overrijke Oogst',
        icoon: '🌾',
        kans: 0.06,
        beschrijving: 'Een uitzonderlijk goede oogst heeft de voedselmarkt overspoeld. Nebulakorrels en Aquapure zijn spotgoedkoop.',
        effect: { type: 'prijsVerlaging', goederen: ['nebulakorrels', 'aquapure'], factor: 0.5 },
    },
    {
        id: 'energiecrisis',
        naam: 'Energiecrisis',
        icoon: '🔋',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een storing in de energiecentrale heeft de haven getroffen. Pyrogel en Kristalliet zijn vandaag extra duur.',
        effect: { type: 'prijsVerhoging', goederen: ['pyrogel', 'kristalliet'], factor: 2.0 },
    },
    {
        id: 'tech_doorbraak',
        naam: 'Technologische Doorbraak',
        icoon: '🔬',
        kans: 0.05,
        beschrijving: 'Lokale wetenschappers maakten een baanbrekende ontdekking. Technoware en Quantumchips zijn tijdelijk 35% goedkoper.',
        effect: { type: 'prijsVerlaging', goederen: ['technoware', 'quantumchips'], factor: 0.65 },
    },
    {
        id: 'piraten_aanval',
        naam: 'Pirateninval',
        icoon: '💀',
        type: 'gevaar',
        kans: 0.04,
        beschrijving: 'Piraten hebben de haven aangevallen tijdens jouw landing. Een deel van je lading is gestolen!',
        effect: { type: 'ladingStelen', fractie: 0.1 },
    },
    {
        id: 'markt_crash',
        naam: 'Lokale Marktcrash',
        icoon: '📉',
        kans: 0.04,
        beschrijving: 'Speculanten hebben de lokale markt doen crashen. Alle goederen zijn vandaag 20% goedkoper — maar kopers zijn ook schaars.',
        effect: { type: 'kortingAlles', factor: 0.8 },
    },
    {
        id: 'zwarte_markt',
        naam: 'Zwarte Markt Actief',
        icoon: '🕵️',
        kans: 0.05,
        beschrijving: 'Een ondergrondse markt biedt Luxuriet en Lunasteen aan voor slechts de helft van de normale prijs. Grijp je kans!',
        effect: { type: 'prijsVerlaging', goederen: ['luxuriet', 'lunasteen'], factor: 0.5 },
    },
    {
        id: 'handelsblokkade',
        naam: 'Galactische Handelsblokkade',
        icoon: '🚫',
        type: 'gevaar',
        kans: 0.03,
        beschrijving: 'Autoriteiten hebben een handelsblokkade uitgevaardigd. Luxe goederen en edelstenen zijn 60% duurder.',
        effect: { type: 'prijsVerhoging', goederen: ['luxuriet', 'lunasteen'], factor: 1.6 },
    },
    {
        id: 'voedselschaarste',
        naam: 'Voedselschaarste',
        icoon: '🆘',
        type: 'gevaar',
        kans: 0.05,
        beschrijving: 'Een mislukte oogst heeft geleid tot ernstige voedseltekorten. Nebulakorrels en Aquapure zijn enorm in prijs gestegen!',
        effect: { type: 'prijsVerhoging', goederen: ['nebulakorrels', 'aquapure'], factor: 2.2 },
    },
    {
        id: 'mijnwerkerstaking',
        naam: 'Mijnwerkerstaking',
        icoon: '✊',
        kans: 0.05,
        beschrijving: 'Mijnwerkers staken voor betere arbeidsomstandigheden. Ferroiet en Kristalliet zijn tijdelijk niet te krijgen voor normale prijs.',
        effect: { type: 'prijsVerhoging', goederen: ['ferroiet', 'kristalliet'], factor: 1.9 },
    },
];
